### ISSUE TITLE
Key combination Ctrl-Shift is not recognized

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#349] opened 2017-03-31 04:00 UTC
In dos environment I use an editor called Multi Edit with an addon named Evolve. 

Inside Multi Edit, to access the Evolve menu we use key combination `Ctrl-Shift-F10` which works well in dosemu1. In dosemu2, this key combination is not recognized. Pressing `Ctrl-Shift-F10` behaves just like pressing `F10`.  `Ctrl-F10` and `Shift-F10` works as expected.

**Comment by stsp** [comment] 2017-03-31 10:00
Please provide more info.
A terminal or sdl mode?
In case of sdl mode, have you tried
Ctrl-Alt-k to grab the keyboard?

**Comment by bpranoto** [comment] 2017-03-31 11:07
Problem is with `dosemu -X`, `dosemu -S` works fine.

**Comment by stsp** [comment] 2017-03-31 12:04
have you tried Ctrl-Alt-k to grab the keyboard?

**Comment by bpranoto** [comment] 2017-03-31 12:23
Just tried `Ctrl-Alt-K` , yes `Ctrl-Shift-F10` works but the cursor shape changes and I can't move the dosemu windows with the mouse

**Comment by stsp** [comment] 2017-03-31 13:20
Cursor shape is now fixed.
I can't reproduce window moving problem.
I can easily move it with the mouse even after
Ctrl-Alt-k.

**Comment by bpranoto** [comment] 2017-03-31 13:47
Regarding windows moving problem, it happened when I run dosemu2 remotely from my laptop through ssh. 

After reading your response I try to run directly in the computer, and yes you're right I can move the window after Ctrl-Alt-K

**Comment by stsp** [comment] 2017-03-31 13:47
Perhaps also locally you don't even need Ctrl-Alt-k?

**Comment by bpranoto** [comment] 2017-03-31 13:57
I git-pull and try again (this time locally):

dosemu -X
Without Ctrl-Alt-K: `Ctrl-Shift-F10` works, but now `Alt-F` doesn't work.
With Ctrl-Alt-K: all works.

dosemu -S
all runs well

**Comment by stsp** [comment] 2017-03-31 14:06
Please run 'xev' and see if Alt-f produces
all the needed events.

**Comment by bpranoto** [comment] 2017-03-31 14:27
```
KeyPress event, serial 22, synthetic NO, window 0x3e00001,
    root 0xd4, subw 0x0, time 37999312, (459,-17), root:(1136,168),
    state 0x10, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

FocusOut event, serial 22, synthetic NO, window 0x3e00001,
    mode NotifyGrab, detail NotifyAncestor

FocusIn event, serial 22, synthetic NO, window 0x3e00001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 22, synthetic NO, window 0x0,
    keys:  4294967252 0   0   0   0   2   0   0   1   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeyRelease event, serial 22, synthetic NO, window 0x3e00001,
    root 0xd4, subw 0x0, time 37999792, (459,-17), root:(1136,168),
    state 0x18, keycode 41 (keysym 0x66, f), same_screen YES,
    XLookupString gives 1 bytes: (66) "f"
    XFilterEvent returns: False

KeyPress event, serial 22, synthetic NO, window 0x3e00001,
    root 0xd4, subw 0x0, time 37999792, (459,-17), root:(1136,168),
    state 0x18, keycode 41 (keysym 0x66, f), same_screen YES,
    XLookupString gives 1 bytes: (66) "f"
    XmbLookupString gives 1 bytes: (66) "f"
    XFilterEvent returns: False

KeyRelease event, serial 22, synthetic NO, window 0x3e00001,
    root 0xd4, subw 0x0, time 37999936, (459,-17), root:(1136,168),
    state 0x18, keycode 41 (keysym 0x66, f), same_screen YES,
    XLookupString gives 1 bytes: (66) "f"
    XFilterEvent returns: False

```

**Comment by bpranoto** [comment] 2017-03-31 14:33
but `right alt f` works, strange...

**Comment by stsp** [comment] 2017-03-31 14:42
So you WM or some app grabs Alt-f.
This is not a dosemu bug.

**Closed by stsp** 2017-03-31 14:42 UTC

**Comment by bpranoto** [comment] 2017-03-31 14:44
Yes, I agree.
