### ISSUE TITLE
mouse oddities with -w

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#376] opened 2017-05-07 21:52 UTC
Browsing the net I found this article, he had to do use a couple of patches to get an ancient touchscreen working -
http://www.fhitc.de/index.php/dosemu-with-linux/?lang=en

- He added an option to default to mousegrab if an envvar was set.

This obviously shouldn't go in as-is, but having an option to start from the commandline with the mouse grabbed could be useful.

This patch to fixup short packets in the TAP

http://www.spinics.net/lists/linux-msdos/msg00821.html

Not sure if this patch is still relevant, but since it looks like it didn't go in at the time, thought I'd flag it here.

**Comment by andrewbird** [comment] 2017-05-07 23:08
TAP patch looks like it's already been applied here.

**Comment by stsp** [comment] 2017-05-08 11:05
Yes, I've found the TAP patch myself a
few years ago and applied it.
Also I can't reproduce the bug from the
first link - fullscreen mode enables mouse
grab in dosemu2.
But I've found several problems while testing
this. Namely:
`dosemu -w -X` gives invisible mouse.
`dosemu -w` gives visible mouse, but the first
click always goes into the corner.
I'll fix those.

**Comment by stuaxo** [comment] 2017-05-08 19:29
I had a quick test with AnimatorPro (320x200 VGA)

https://github.com/AnimatorPro/Animator-Pro/downloads

Also with a demo simcity2000 (640x480 VESA)

http://www.dosgamesarchive.com/download/simcity-2000/

The mouse position seems incorrect when using it without mousegrab.

It can correctly go to the top-left corner, but only goes so far into the window before hitting the hosts window edge, this seems to be dependent on the DOS resolution.

**Comment by stsp** [comment] 2017-05-09 16:33
We usually do not consider non-grab mode
problems as bugs. DOS programs can maintain
their own resolution that doesn't match the one
of the host. If in grab mode it works correctly and
has similar sensitivity as in non-grab mode, then
this is the best we can aim for.

**Comment by stsp** [comment] 2017-06-16 00:00
`dosemu -w -X` is now fixed, but `dosemu -w`
is something completely undebugable.
Some very obscure SDL bug it seems.
Maybe related to #350

**Closed** 2017-09-03 23:00 UTC
