### ISSUE TITLE
Keyboard layout not detected ..

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#71] opened 2015-08-25 09:50 UTC
I use "English (UK, Extended, Winkeys)" in gnome on Linux any idea how I can get dosemu to be able to detect my UK keyboard ?

On startup I get:
```
ERROR: Unable to open console or check with X to evaluate the keyboard map.
Please specify your keyboard map explicitly via the $_layout option.
Press ENTER to continue with DOS programs thinking that they use a US layout or
Ctrl-C to exit.
```

**Comment by andrewbird** [comment] 2015-08-25 10:00
I expect the console check to fail always, unless you are root or have opened up the permissions on the console. X is another thing however.
- Are you running in X?
- Is the DISPLAY variable set?
- Are you local or remote?
- Does starting 'xterm' succeed?

**Comment by stsp** [comment] 2015-08-25 10:34
> I expect the console check to fail always, unless you are root

But on fedora:
$ ls -l /dev/tty
crw-rw-rw-. 1 root tty 5, 0 Aug 25 12:32 /dev/tty

Is this a problem on ubuntu only?
Please show your perms on /dev/tty.

As for X - I am puzzled too.
-D9+kcX log could help.

Alternatively you can check the code and see why
X11_DetectLayout() returns non-zero. It looks like
the only possibility for this is if XOpenDisplay() failed.

**Comment by andrewbird** [comment] 2015-08-25 10:47
Ubuntu 14.04 has
~~~
ajb@polly:~$ ls -l /dev/tty
crw-rw-rw- 1 root tty 5, 0 Aug 25 08:20 /dev/tty
~~~

But I still get 
~~~
KBD: keyb_server_init()                                                         
KBD: setup_default_keytable: setting up table 35                                
setup_default_keytable: failed to read kernel console keymap                    
~~~

Which I don't remember ever working for me, which is why I was keen on getting #43 fixed. So reading the kernel console keymap works for you as non root?

**Comment by stsp** [comment] 2015-08-25 10:56
Yes, absolutely.

2517	  /* Now copy parameters for the linux kernel keymap */
2518	  if(read_kbd_table(kt, altkt)) {
2519	    k_printf("setup_default_keytable: failed to read kernel console keymap\n");
2520	    kt->name = NULL;
2521	  }
2522	
(gdb) n
2526	  handle = load_plugin("X");
(gdb) p kt->name
$3 = 0x569a5e "auto"

As you can see from this gdb session, I have
kt->name="auto" rather than NULL on failure.
Could you please check where does it fail on
ubuntu and why?

Hmm, supporting ubuntu looks more troubles
than profit. :)

**Comment by andrewbird** [comment] 2015-08-25 11:15
Okay, so there appear to be two issues. I'll look at why the reading the console keymap doesn't work as non root on Ubuntu since I can reproduce that.

**Comment by andrewbird** [comment] 2015-08-25 11:35
The is_console() function is using ioctl KDGKBTYPE on /dev/tty, but it returns -1 and sets errno to "Inappropriate ioctl for device". Just so I am clear, is this supposed to work in an xterm as well as on a VT?

**Comment by stsp** [comment] 2015-08-25 11:52
Same happens for me too, BUT, it then tries
/dev/tty0 and that works because I am in a tty group.
$ ls -l /dev/tty0
crw--w----. 1 root tty 4, 0 авг 25 12:32 /dev/tty0

Slightly better than requiring root at least...

**Comment by stsp** [comment] 2015-08-25 11:58
What does dumpkeys cmd tells you?

**Comment by andrewbird** [comment] 2015-08-25 11:58
Okay, then it is a permissions thing, since I am not in the tty group and I don't believe tty is in the default set that Ubuntu issue new users. I don't think any change is necessary, unless you want to add some help hint into the boot.log?

~~~
ajb@polly:~$ dumpkeys 
Couldn't get a file descriptor referring to the console
~~~

**Comment by stsp** [comment] 2015-08-25 12:00
OK, does at least
dosemu -s
work right?

**Comment by andrewbird** [comment] 2015-08-25 12:10
No, I'm afraid not. Interesting that even sudo couldn't open /dev/tty0
 
~~~
KBD: keyb_server_init()                                                         
KBD: setup_default_keytable: setting up table 35    
                            
ioctl returned -1 - Inappropriate ioctl for device                              
ioctl returned ^@ (KB_101 == ^B), (KB_84 == ^A)                                 
is_a_console failed                                                             
open_a_console failed on /dev/tty 
                                             
open O_RDONLY failed with error Permission denied                               
open O_WRONLY failed with error Permission denied                               
open_a_console failed on /dev/tty0    
                                          
open O_RDONLY failed with error No such file or directory                       
open_a_console failed on /dev/vc/0       
                                       
open O_RDONLY failed with error Permission denied                               
open O_WRONLY failed with error Permission denied                               
open_a_console failed on /dev/console  
                                                                  
setup_default_keytable: failed to read kernel console keymap                    
~~~

**Comment by andrewbird** [comment] 2015-08-25 12:19
I just did a further test by adding a main() to getfd.c and compiling it separately
~~~
ajb@polly:/tmp$ sudo ./a.out 
ioctl returned -1 - Inappropriate ioctl for device
ioctl returned  (KB_101 == ), (KB_84 == )
is_a_console failed
open_a_console failed on /dev/tty

ioctl returned 0 - Success
ioctl returned  (KB_101 == ), (KB_84 == )
~~~

Which shows that it works on /dev/tty0 when the resulting binary is run with just plain sudo. Maybe there's something odd in the way the -s option invokes sudo?

**Comment by andrewbird** [comment] 2015-08-25 12:39
Further info if I avoid the startup script and run dosemu.bin directly with sudo it will start up. It seems only the dosemu script has issues believing it should be able to write to my NFS home.

~~~
sudo -E /opt/dosemu2/bin/dosemu.bin -X -p  -D+k
~~~

But /dev/tty0 is still in accessible, whereas my standalone 'getfd' program can access it fine.

**Comment by stsp** [comment] 2015-08-25 12:53
dosemu does priv_drop(), after which root
access is not possible. There is keyb_priv_init()
which should be modified to open a tty and
save its fd in a var. getfd() will then just return
that var.
Additionally, the priv code should be between
enter_priv_on() and leave_priv_setting().

**Comment by andrewbird** [comment] 2015-08-25 14:21
I have to go out now. If you put the -s fix in a branch I can test it later when I return

**Comment by stsp** [comment] 2015-08-25 14:47
Done.

**Comment by andrewbird** [comment] 2015-08-25 19:58
The semi-issue of whether dosemu -s can read the console keymap is fixed by https://github.com/stsp/dosemu2/tree/cons_fd and in my opinion is good to merge

Now we need followup from the reporter on why probing the X keymap failed, so

-    Are you running in X?
-    Is the DISPLAY variable set?
-   Are you local or remote?
-    Does starting 'xterm' succeed?

**Comment by stsp** [comment] 2015-08-25 20:21
Please add "does the dosemu -s succeeded" to
the list of questions. :)

**Comment by andrewbird** [comment] 2015-08-25 20:48
Now we need followup from the reporter on why probing the X keymap failed, so
-    Are you running in X?
-    Is the DISPLAY variable set?
-   Are you local or remote?
-   Does starting 'xterm' succeed?

And if you use the 'cons_fd' branch
 - Does 'dosemu -s' succeed in setting the keymap correctly?

**Comment by stuaxo** [comment] 2015-08-26 06:59
Hi,
    Been travelling - it's been great to see this each time I've managed to get on the net..

- I am running under X
- DISPLAY is set to :0
- running locally
- xterm can starts ok, runs powerline prompt fine

On the cons-fd branch, it seems to works with ```dosemu -s```

**Comment by stuaxo** [comment] 2015-08-26 07:12
Ah, was having some trouble building (I installed make:i386 before and that uninstalled useful stuff like SDL2) - have rebuilt and the keyboard detection works now (in devel, with a normal user, not using dosemu -s)

**Comment by stuaxo** [comment] 2015-08-26 07:17
Works for me (TM) can shut.

**Comment by andrewbird** [comment] 2015-08-26 07:59
I don't suppose you still have a log of which packages were installed just before it started working?

**Comment by stsp** [comment] 2015-08-26 10:32
#ifdef X_SUPPORT
int X11_DetectLayout (void);
#endif

He simply didn't have xlib headers installed
at some point, and then - haven't regenerated
configure, so X was still not built (SDL was used).
We really need to provide at least the needed m4
scripts, or the problems are too subtle.

**Closed by stsp** 2015-08-26 10:32 UTC
