### ISSUE TITLE
Holiday Lemmings '94 horizontal mouse resolution issues (vertical is ok)

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#217] opened 2016-07-26 20:15 UTC
When playing Holiday Lemmings '94 in VGA mode, the whole screen is reachable, but the host pointer does not seem to be in sync horizontally with the game's pointer. The game does seem to use INT33 as it repositions the cursor when you enter the window from another edge.

More info about the game: http://www.abandonia.com/en/games/234/Holiday+Lemmings+Pack.html

**Comment by stsp** [comment] 2016-07-26 21:15
Is this a regression?

**Comment by jschwartzenberg** [comment] 2016-07-27 20:18
No, not a regression, 1.4 has the same behavior.

**Comment by stsp** [comment] 2016-07-28 09:36
Does moving out of the window and back in
gets it in sync?

**Comment by jschwartzenberg** [comment] 2016-07-28 15:32
No, the cursor appears at the wrong horizontal position when the mouse enters the window.

**Comment by jschwartzenberg** [comment] 2016-08-08 19:46
This game also seems to try to increase the speed for just one direction. It was probably meant to be played with a non-square pixel aspect ratio as well (like Sim City).

**Comment by stsp** [comment] 2016-08-14 18:42
Then this is probably not a bug.
If you can check with the native mouse driver
and it shows the speed increase, then please
close this.

**Comment by stsp** [comment] 2016-08-14 18:51
Or make it otherwise: you re-open it if the
bug is confirmed.

**Closed by stsp** 2016-08-14 18:51 UTC

**Comment by jschwartzenberg** [comment] 2016-08-14 20:41
I can't reopen bugs here, but I'll look into it.

**Comment by stsp** [comment] 2016-08-15 15:10
Yes, free github accounts do not seem to give any extended
permission control.
