### ISSUE TITLE
Dosemu console only, framebuffer issue

### ISSUE THREAD

**Issue by mikedebian** [stsp/dosemu2#397] opened 2017-06-18 17:24 UTC
Dosemu git version [0417a64](https://github.com/stsp/dosemu2/commit/0417a648a5be63bff4c5a4ced5f9ca35ebabd4ad) compiled with experiment options and ----disable-xbacktrace.

Dosemu fails to load under console. Is dosemu using fbdev? Links using fb works, but mplayer has to use fbdev2 in order to display video.

I attached boot.log as out.log.txt
[out.log.txt](https://github.com/stsp/dosemu2/files/1083238/out.log.txt)

dmesg output of console and fb0, if relevant:

```
[    0.000000] console [tty0] enabled
[    2.647180] fb0: VESA VGA frame buffer device
[    6.142187] fbcon: amdgpudrmfb (fb0) is primary device
[    6.356873] amdgpu 0000:29:00.0: fb0: amdgpudrmfb frame buffer device
```

**Comment by stsp** [comment] 2017-06-18 17:36
try `dosemu -s`

**Comment by mikedebian** [comment] 2017-06-18 17:53
Attached is with output dosemu -s
[out.log.txt](https://github.com/stsp/dosemu2/files/1083250/out.log.txt)

**Comment by stsp** [comment] 2017-06-18 18:02
I disabled this sdl fallback as it doesn't work.
In video.c:198 you can try to completely disable
the kms check by removing the first `if` and its
code, and then run `dosemu -s` again. But be
prepared to the whole system freeze, save your
data.

**Comment by mikedebian** [comment] 2017-06-18 18:13
dosemu -s. removed if and code from video.c line 198

[out.log.txt](https://github.com/stsp/dosemu2/files/1083254/out.log.txt)

**Comment by stsp** [comment] 2017-06-18 18:15
No, you didn't remove the code block, because
there is still `KMS detected: using terminal mode.`
in the log. You had to remove lines from 198 to 209.

**Comment by mikedebian** [comment] 2017-06-18 18:19
I am truly sorry. Here is the new log. Removed lines 198-209.

dosemu -s

[out.log.txt](https://github.com/stsp/dosemu2/files/1083257/out.log.txt)

**Comment by stsp** [comment] 2017-06-18 18:21
Please use `dosemu -s -D9+cv` to get more logging.

**Comment by mikedebian** [comment] 2017-06-18 18:25
Attached new log

[out.debug.txt](https://github.com/stsp/dosemu2/files/1083264/out.debug.txt)

**Comment by stsp** [comment] 2017-06-18 18:40
I added a bit more logging, please repeat the log.

**Comment by mikedebian** [comment] 2017-06-18 18:58
New log file attached.

[out1.debug.txt](https://github.com/stsp/dosemu2/files/1083279/out1.debug.txt)

**Comment by stsp** [comment] 2017-06-18 19:15
I think you have non-default config.
In particular you altered console settings.

**Comment by mikedebian** [comment] 2017-06-18 19:21
You are correct, sorry. I commented out all modified settings on #console.

It locked as you predicted, but no worries.
Here's the new logfile.

[out2.debug.txt](https://github.com/stsp/dosemu2/files/1083307/out2.debug.txt)

**Comment by stsp** [comment] 2017-06-18 19:23
Please attach `lspci -v`

**Comment by mikedebian** [comment] 2017-06-18 19:26
[lspci.log.txt](https://github.com/stsp/dosemu2/files/1083310/lspci.log.txt)

Attached is lspci -v output.

**Comment by stsp** [comment] 2017-06-18 19:39
Added a bit more logging, please use
`dosemu -s  -D9_cvZ`

**Comment by mikedebian** [comment] 2017-06-18 20:48
```
commit 17bc5a32b535c074075c99a6a52ce76a86a05d01 (HEAD -> devel)
Author: Mikaël Xavier Lied <mxl@nmcl.no>
Date:   Sun Jun 18 22:37:19 2017 +0200

    Revert "video: sdl is hopeless with kms so try term [#397]"
    
    This reverts commit 63ecbe015df4fbbf8d3df958da7dc3d5b9990128.
```

video.c before removing of lines
[log.before.line.removal.txt](https://github.com/stsp/dosemu2/files/1083361/log.before.line.removal.txt)


video.c after removing of lines
[log.after.line.removal.txt](https://github.com/stsp/dosemu2/files/1083362/log.after.line.removal.txt)

**Comment by stsp** [comment] 2017-06-18 21:08
No, the revert was needed for another
report, not here.
It seems there is a memory corruption
in the pcibios code, probably now fixed.
Please re-do the log.

**Comment by mikedebian** [comment] 2017-06-18 21:14
Sorry, I thought it was meant for this. I will redo. Also, you wrote:

> dosemu -s -D9_cvZ
_ is an unknown flag
I suppose you meant + and not _

Either way, it works now. Here's a before and after log

I should note that when dosemu is running on tty0, it crashes X on tty7. After exiting dosemu with ctrl+alt+pgdwn, I can return to X, however it seems that it is now using software renderer and is slow as molasses.

[log.before.line.removal.txt](https://github.com/stsp/dosemu2/files/1083385/log.before.line.removal.txt)
[log.after.line.removal.txt](https://github.com/stsp/dosemu2/files/1083387/log.after.line.removal.txt)

**Comment by stsp** [comment] 2017-06-18 21:19
Wow! I am really surprised it worked. :)
And you machine have not even locked
up afterward, excellent.
So if you run X in another tty, why not to
run dosemu inside these X then?

**Comment by stsp** [comment] 2017-06-18 21:19
And yes, I indeed meant `+`

**Comment by mikedebian** [comment] 2017-06-18 21:25
Well, I wanted to see if running it fullscreen in console was possible. It's supposed to be possible, so why not? :) Is that wrong? I sometimes run without X as well, using only the console and apps within console.


Running dosemu in terminal mode (no graphics) results in sound working. Just text though.
It used to lock up tty0 before when I started a game like for example Skyroads, now it just shows a blinking cursor while it plays the music. I can exit the game and dosemu, no problem.

No sound with -s though.

Seperate issue?

**Comment by stsp** [comment] 2017-06-18 21:34
> It's supposed to be possible, so why not? :)

The problem is in sdl2 builds that in most (or all)
distros have disabled the directfb backend. It is
possible to reenable sdl1 support, but this is an
extra maintenance burden for me. Please ask your
distro to re-enable the directfb support in sdl2.
And just today I disabled this too because you
had the crash. If we can fix this crash and your
distro will rebuild sdl2 with directfb support, then
we'll have a cool full-screen console capability.

> No sound with -s though.

Yes, a separate issue.

**Closed** 2017-06-18 21:34 UTC

**Comment by mikedebian** [comment] 2017-06-18 21:42
I understand. Shame with SDL2 backend though. Can't it use another backend, like mplayer or links does (fb or fbdev2)? I have no idea if this is possible or how it works. If it's a laughable suggestion, just move on.

Thank you very much for fixing the bug though. :)

I don't think I'll use the -s function that much, as it has locked up the machine after a few tries.

**Comment by stsp** [comment] 2017-06-18 21:47
Another backend is possible but someone has
to write the code for it. Since SDL is supposed
to do so and even has all the code in place,
just disabled by distributors, I am a bit reluctant
to write such backend myself.

**Comment by stsp** [comment] 2017-06-18 21:48
You can make `-s` not to crash your machine.
You need to disable KMS with `nomodeset`
kernel parameter, and you need to enable
magic sysrq keys. Then you are safe with
the quite high probability. :)

**Comment by mikedebian** [comment] 2017-06-18 21:49
I see, I will do this. Not tonight though. I'll open a separate issue tomorrow. Thanks for doing this (dosemu2)!

**Comment by stsp** [comment] 2018-02-04 19:48
I added the full console support with sdl1 plugin.
Please see if it works for you properly.
