### ISSUE TITLE
exitemu doesn't do anything

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#67] opened 2015-08-24 19:24 UTC
exitemu doesn't seem to do anything.

On devel branch, 64 bit Ubuntu 15.04

**Comment by stsp** [comment] 2015-08-24 20:44
As well as any other built-ins for you.
When you replace generic.com from "good"
version, it will start working.
Lets close this as a dupe of #64 .

**Closed by stsp** 2015-08-24 20:44 UTC
