### ISSUE TITLE
siedler2: dosemu 'Aborted'

### ISSUE THREAD

**Issue by fguzm** [stsp/dosemu2#39] opened 2015-06-26 06:09 UTC
dosemu.bin: coopth.c:300: get_pth: Assertion `idx >= 0 && idx < 5' failed.

**Comment by stsp** [comment] 2015-06-26 16:45
In git, dosemu will now properly log such an events.

**Comment by fguzm** [comment] 2015-06-27 04:21
still the same error dosemu.bin: coopth.c:300: get_pth: Assertion `idx >= 0 && idx < 5' failed.
and in rapidly closing dosemu window, the error message is
unhandled exeption - terminating client
it is likely that dosemu should be robooted (or something similar, closing too fast to read)

debian testing
btw why 'meaningless report'?

**Comment by stsp** [comment] 2015-06-27 09:00
Because it lacks the description, ways
to reproduce, and dosemu log.
Unfortunately, I haven't written the doc
about how to report bugs; the event was
not logged anyway (this is now fixed), and,
what is the worst, github doesn't even allow
to attach files to the bug reports! So I don't
even know how to change the situation,
and in a mean time, many other reports
have similar problems.

Now as to the log: the only way I know you
can attach it here, is to reply to this by e-mail
and attach the log to the reply. github then
will display it as if it was copy/pasted.

**Comment by stsp** [comment] 2015-06-27 12:22
You can also mail me the log directly.
(github sucks)

**Comment by fguzm** [comment] 2015-06-27 17:03
I know from other projects on github that they use pastebin for such.
Here is my dosemu log:
http://pastebin.com/9hUwqYP9

**Comment by stsp** [comment] 2015-06-27 17:32
Indeed, more useful than inlining it here.
Your dosemu is not compiled with debug info.
Please try
make clean
./default-configure -d
make -j 4

**Comment by fguzm** [comment] 2015-06-28 05:14
http://pastebin.com/nQ6Y07hP

**Comment by stsp** [comment] 2015-06-28 10:21
There are some problems.
Firstly debug info is still not enabled, and
secondly it seems you need to run
./autogen.sh
before re-building.
I've added the makefile rule now to regenerate
configure automatically, so try again.

**Comment by fguzm** [comment] 2015-06-28 13:03
xxx@xxx:~$ gdb /usr/local/bin/dosemu.bin
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/dosemu.bin...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/local/bin/dosemu.bin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff39d9700 (LWP 20305)]
[New Thread 0x7ffff30be700 (LWP 20306)]
[New Thread 0x7ffff24b5700 (LWP 20307)]
fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
[New Thread 0x7fffe0ee4700 (LWP 20308)]
[New Thread 0x7fffdc6e2700 (LWP 20309)]
[Thread 0x7fffdc6e2700 (LWP 20309) exited]
[New Thread 0x7fffdc6e2700 (LWP 20310)]
[Thread 0x7fffdc6e2700 (LWP 20310) exited]
[New Thread 0x7fffdc6e2700 (LWP 20311)]
[Thread 0x7fffdc6e2700 (LWP 20311) exited]
[New Thread 0x7fffdc6e2700 (LWP 20312)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fdf542 in ?? ()
(gdb)

**Comment by stsp** [comment] 2015-06-28 13:13
> Reading symbols from /usr/local/bin/dosemu.bin...(no debugging symbols found)...done.

Please fix this.

**Comment by fguzm** [comment] 2015-06-28 13:20
I am not a computer expert, just a user.
I do not know what to do other than ./default-configure -d

**Comment by stsp** [comment] 2015-06-28 13:42
Please show the last log.

**Comment by stsp** [comment] 2015-06-28 13:43
From today's git

**Comment by fguzm** [comment] 2015-06-28 16:21
http://pastebin.com/LmiN3r7W

**Comment by stsp** [comment] 2015-06-28 16:28
The log is indeed up to date, but still no debug info.
I don't believe you do ./default-configure -d
Please post the full build log from terminal.

**Comment by stsp** [comment] 2015-06-28 22:40
The problem is likely that you refused to run
./autogen.sh
despite I asked you to a few times.
As a result, makefile did that for you, but then
restarted configure without debug info.

Rebuilding once again should fix the problem.

**Comment by fguzm** [comment] 2015-06-29 05:49
I'm afraid that there is still no debug info.
http://pastebin.com/yCz8yzK1

**Comment by andrewbird** [comment] 2015-06-29 08:45
Hi both,
  I think it's the checkinstall that's stripping the debug info from the packaged binaries. Try using 
checkinstall --fstrans=no --stripso=no --strip=no

Hope it helps,


Andrew

**Comment by fguzm** [comment] 2015-06-29 09:18
Here we go
http://pastebin.com/peMw17Ye

**Comment by stsp** [comment] 2015-06-29 09:58
OK, I hope the assert is now avoided.
Would you mind explaining how to reproduce the problem?
Also it would be interesting to know if you can reproduce
it with dosemu-1:
http://sourceforge.net/p/dosemu/code/ci/devel/tree/

**Comment by fguzm** [comment] 2015-06-29 12:55
forgot to mention that checkinstall --fstrans=no --stripso=no --strip=no dit the trick, thx andrewbird

**Comment by fguzm** [comment] 2015-06-29 13:00
Now dosemu2 crashes with ERROR: coopth: schedule to inactive thread

**Comment by stsp** [comment] 2015-06-29 13:16
Yes, that's expected.
Better than assert.

**Comment by fguzm** [comment] 2015-06-29 15:22
Dosemu1 crashes too! So the devil is in my computer?


CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing built-in global.conf file.
CONF: config variable version_3_style_used unset
CONF: config variable version_3_style_used set
CONF: opened include file /etc/dosemu/dosemu.conf
CONF: closed include file /etc/dosemu/dosemu.conf
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: Disabling use of pentium timer
CONF: dosbanner on
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: JIT CPUEMU set to 0 for 586
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe400
CONF: DPMI-Server on (0x5000)
CONF: DPMI base addr = 0xffffffff
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: off
CONF: 8192k bytes XMS memory
CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
CONF: Keyboard-layout keyb-user
CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -l -P lpt2  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
device: /home/roje/.dosemu/drives/c type 4 h: -1  s: -1   t: -1 drive C:
device: /home/roje/.dosemu/drives/d type 4 h: -1  s: -1   t: -1 drive D:
CONF: cdrom MSCD0001 on /dev/cdrom
CONF: config variable c_system unset
Linux kernel 4.1.0; CPU speed is 1800000000 Hz
CPU-EMU speed is 1800 MHz
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1000 (cached 1000)
DBG_FD already set
DOSEMU-1.4.0.8-180-g35054ba is coming up on Linux version 4.1.0 #1 SMP Mon Jun 22 11:58:30 CEST 2015 x86_64
Compiled with GCC version 4.9.2 -m64
WARN: vm86plus service not available in your kernel
WARN: using CPU emulation for vm86()
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 48Kb at 0xF4000 for 'r' (Dosemu reserved area)
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
PKT: Cannot open raw sockets: No such file or directory
WARN: using non-zero memory base address 0x10f000.
WARN: You can use the better-tested zero based setup using
WARN: sysctl -w vm.mmap_min_addr=0
WARN: as root, or by changing the vm.mmap_min_addr setting in
WARN: /etc/sysctl.conf or a file in /etc/sysctl.d/ to 0.
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))
Registering HWRAM, type=e base=0x40cf5000 size=0x400000
CONF: reserving 4096Kb at 0x40CF5000 for 'e' (VGAEMU LFB)
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
SERIAL $Id$
fluidsynth: cannot load soundfont /usr/share/soundfonts/default.sf2
CONF: detected layout is "de-latin1"
CONF: detected alternate layout: de-latin1
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xF0000 for 'E' (EMS page frame)
CONF: reserving 132Kb at 0xC3000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
TIME: using 9154 usec for updating ALRM timer
======================= ENTER CPU-EMU ===============

leavedos(Interp86|3056) called - shutting down
======================= LEAVE CPU-EMU ===============

**Comment by stsp** [comment] 2015-06-29 15:26
> Dosemu1 crashes too! So the devil is in my computer?

Nothing can be said as you didn't reveal the ways to
reproduce, despite being asked.

You can also try dosemu1 tag dosemu-1.4.0.8, which
was the last release of dosemu1.

**Comment by fguzm** [comment] 2015-06-29 19:25
I enter dosemu, in the now popping up window I cd to the s2 folder, then I execute s2.
Then dosemu crashes. Thats it. Or what do you mean with steps to reproduce?
My system is debian 64bit, testing repository.

**Comment by stsp** [comment] 2015-06-29 21:34
Because other people have no problems playing s2,
see here for instance:
https://github.com/stsp/dosemu2/issues/22
Maybe you have something wrong in your
autoexec.bat/config.sys, in which case you
can press F5 at early dosemu startup to bypass
them.
Maybe you have something wrong in settlers
setup: wrong sound card parameters, for example.
Maybe you have outdated dos4gw... what version?

**Comment by stsp** [comment] 2015-06-30 12:34
Also please attach the -D9+M log

**Comment by fguzm** [comment] 2015-07-01 03:43
On my other computer with the same system settings dosemu runs flawless... thx anyway

**Comment by stsp** [comment] 2015-07-01 11:32
So what's the difference?
Would you provide the -D9+M log, or should I close?

**Comment by fguzm** [comment] 2015-07-01 14:05
-D9+M? What is that?

**Comment by stsp** [comment] 2015-07-01 14:06
dosemu -D9+M

**Closed** 2015-07-01 14:38 UTC
