### ISSUE TITLE
PC-MOS/386 in DOSEMU2?

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#502] opened 2017-10-23 07:53 UTC
I just saw this news, maybe it'll be possible to run this in DOSEMU:
https://news.slashdot.org/story/17/10/22/1938209/30-year-old-operating-system-pc-mos386-finally-
open-sourced

Here is the source: https://github.com/roelandjansen/pcmos386v501
It currently requires a Borland compiler.
I guess it would already be a good step to have the build fully working inside DOSEMU.

**Comment by andrewbird** [comment] 2017-10-23 09:32
If you read some of their [issues](https://github.com/roelandjansen/pcmos386v501/issues/8), it seems like there are some original developers of it taking an interest.

**Comment by andrewbird** [comment] 2017-10-23 10:56
Boots from floppy, but doesn't like our fatfs images even being present.
![pcmos-floppy](https://user-images.githubusercontent.com/220835/31884824-53db3686-b7e6-11e7-9e39-076484316fad.png)

Disabling MFS behind scenes redirector in init code allows it to continue to boot prompt and see the FATFS C: drive.
![pcmos-fatfsok](https://user-images.githubusercontent.com/220835/31885624-0bd1bd12-b7e9-11e7-8478-d0d93eef0afb.png)

**Comment by stsp** [comment] 2017-10-23 11:18
Wow! I am completely confused.
Wikipedia says it is a 386-specific OS
that uses MMU, and yet it works under
dosemu??

> Boots from floppy, but doesn't like our fatfs images even being present.
> Disabling MFS behind scenes redirector in init code allows it to continue
> to boot prompt and see the FATFS C: drive.

Confused again, so it doesn't like our mfs,
not fatfs? Does it pass all mfs checks for the
compatible DOS version or what?

> I guess it would already be a good step to have the build fully working inside DOSEMU.

The very secret fact is that I know how to
embed freedos inside dosemu. This just
requires a bit of coding efforts, which I don't
have because bugfixing takes too much. :(

**Comment by andrewbird** [comment] 2017-10-23 11:30
> Confused again, so it doesn't like our mfs, not fatfs?

Yes, I messed up there, I half wrote the post before discovering MFS was the issue not fatfs. Of course MFS is only autostarted if there are fatfs, and I'm just too eager!

> Does it pass all mfs checks for the compatible DOS version or what?

Currently it is detected as having a PC-DOS 4 compatible redirector, which I think is the default if detection was inconclusive and the CDA pointer wasn't NULL. 

I will see if I can get booting from FATFS working first, then try to figure out if MFS redirector is usable.

**Comment by stsp** [comment] 2017-10-23 11:35
> I will see if I can get booting from FATFS working first, then try to figure out if MFS redirector is usable.

That would be cool, thanks!

**Comment by dcoshea** [comment] 2017-10-23 11:40
> I guess it would already be a good step to have the build fully working inside DOSEMU.

Oh yes, I should try this, it should be much nicer than the other options I tried (see https://github.com/roelandjansen/pcmos386v501/issues/8).  I can't imagine it should be very challenging.  I doubt any of the compilers require DPMI or anything "scary" like that.

**Comment by stsp** [comment] 2017-10-23 11:47
@dcoshea All DOS compilers to the date
(bc 3.1, djgpp, even nasm) do require DPMI,
but its not scary at all! It works very well
under dosemu2, properly tested and maintained.
Yes, we submit patches to lkml about it, but
for linux-3.10 we have most of the needed
work-arounds in place.
Note that even openwatcom uses dosemu
during the build process (sadly not dosemu2).
So please just try it out.

Could you possibly explain why the OS that
is claimed to be 386-specific and to use MMU,
works under dosemu2 at all? It shouldn't! :)

**Comment by stsp** [comment] 2017-10-23 19:22
After some googling it seems you need to do
`memdev = \mos\$386.sys /p` for it to start using
protected mode. This may be similar to loading
emm386.exe under normal DOS.
So I think wikipedia is wrong on saying
`It required a memory management unit (MMU) to support memory protection, so was not compatible with 8086 and 8088 processors.`
And looking in various .ASM files of mos, I can
mostly see the 16bit realmode assembler.

**Comment by stsp** [comment] 2017-10-23 19:24
https://virtuallyfun.com/2011/02/02/pc-mos386/
`PC-MOS 5.0 also cannot run DPMI programs, which is a shame.`
Hmm. I wonder what does this mean - that they
do not provide the DPMI server by themselves,
or that any other DPMI server cannot be used...

**Comment by andrewbird** [comment] 2017-10-24 22:32
Currently I have it (all with MFS disabled at the moment)
- booting from fatfs hdtype1 with extracted boot.blk (I think your #503 made this happen)
- booting from fatfs hdtype1 without boot.blk, but strangely prompt shows [A:] but files/volume name are from C: so not quite right yet!

Investigating now to find the minimal set of files required to boot ($$mos.sys, $$shell.sys, command.com + at least one other I haven't determined yet)

**Comment by andrewbird** [comment] 2017-10-24 22:52
No it's something more subtle than a missing file. it seems that even with a boot.blk it's finding some of the boot files from the floppy, otherwise it fails to boot. I'll try it with a fatfs floppy, just to confirm which files are being used.

**Comment by andrewbird** [comment] 2017-10-24 23:08
Even when booting off fatfs C: (with boot block) it looks to A: for command.com. What could be doing this, I could understand it with our 32bit boot code, but not with native boot.blk. Here's what's in the boot block - looks fine to me.
~~~
$ ./prbootblk test-imagedir/dXXXXs/mos-bare/boot.blk 
     512 Bytes per sectors
       8 Num sectors per unit
       1 Num reserved sectors
       2 Num FATs
     512 Num root entries
   20791 Num sectors total
      f8 Media descriptor byte
       8 Num sectors in FAT
      17 Num sectors per track
       4 Num heads
      17 Hidden Blocks
      80 Drive number(>4.0) 
~~~

**Comment by andrewbird** [comment] 2017-10-25 00:01
Checking the log for DISK 00 access, I see none. So I renamed the a:\command.com, and it still boots. So it seems that to boot from the hd there must be a floppy, but it can be empty.

**Comment by stsp** [comment] 2017-10-25 09:15
See `bios_mem_setup()`, it does:
`CONF_NFLOP(bios_configuration, config.fdisks);`
Does this help?

**Comment by andrewbird** [comment] 2017-10-25 18:15
Here's an update (all with MFS disabled at the moment) 

- booting ok from fatfs hdtype1 with extracted boot.blk
  - Requires floppy to be present.
- booting ok from fatfs hdtype1 without boot.blk.
  - The strange prompt issue is now fixed. PC-MOS stores the boot drive number at offset 0x3f(immediately following v4 BPB) in VBR instead of passing it in DL. There's unused space at that position in our custom boot block, so it can be added quite easily.
  - Requires floppy to be present.
- boot crashes dosemu from hdimage type1 size (made by native tools hdsetup, format, msys c:, copy $$mos.sys $$shell.sys command.com c:)

~~~
Setting $floppy_a = ""
CONF_NFLOP(bios_configuration, 1);
~~~
This allows booting, though as you might expect MOS doesn't like it if you try to access it
![pcmos-no-floppy-bios_config-tweak](https://user-images.githubusercontent.com/220835/32015050-d325898c-b9b7-11e7-9339-1a3b33b0e51c.png)

So what does that mean, PC-MOS can only work on machines that have a floppy attached, or is there something else?

I guess I need to debug the hdimage boot failure, that's a pretty major failure. Although I could have made it wrong, as I didn't find a tool to do it for me, I did extract the boot.blk fine and subsequently use it for fatfs testing.

**Comment by andrewbird** [comment] 2017-10-25 18:44
Regarding booting from a hdimage, there seems to be a related issue on their tracker https://github.com/roelandjansen/pcmos386v501/issues/1 so I might just wait and see how that evolves?

So that aside, I have two issues to solve; floppy required; and MFS redirector

**Comment by stsp** [comment] 2017-10-25 20:58
About floppy: a spent a few hours
on reading their asm (sigh) and found
this:
```
isdrive proc
...
        int     11h                     ; get equipment information
        test    al,1                    ; any diskettes?
        jnz     isdrives                ; yes count them
        jmp     isdxit                  ; none just exit
isdrives:
        and     ax,00c0h                ; maximum diskette drive number
        rol     al,1                    ; make it an integer
        rol     al,1
        mov     [maxdrv],al
...
isdxit:
        pop     bx
        ret
isdrive endp
...
finitblk proc near
...
        call    isdrive                 ; count disk drives
        pop     es
        mov     al,[maxdrv]
        or      al,al                   ; cmp al,0
        jnz     fini10                  ; if no drives or > 1 drive
```

So in function `isdrive` they put max available
floppy number to `maxdrv`, or, if there are no
floppies, just exit (forgetting to write -1 to `maxdrv`).
In function `finitblk` they check `maxdrv` but
in case of no floppies it does not actually follow
the `jnz` as advertised because `maxdrv` still
contains 0.
Note: I haven't verified this, so I may be wrong.
But looks like an obvious bug.
I also fixed an obvious bug in dosemu's cmos:
it seems the floppy params were wrongly shifted.

**Comment by stsp** [comment] 2017-10-25 21:01
Ah, a minute later found this:
`maxdrv          db      -1      ; maximum drive number in use (-1 means none)`
So the above looks correct then. :(

**Comment by andrewbird** [comment] 2017-10-25 21:15
On your search through the asm, did you stumble across the redirector code?

**Comment by stsp** [comment] 2017-10-25 21:25
No and grep for regexp `int[\t ]+2f` gives nothing.

**Comment by stsp** [comment] 2017-10-25 21:39
A possible problem is here:
```
fini10:
        mov     bx,[hdr]
        inc     al                      ; maximum drive number --> # of units
        mov     es:[bx].irUnits,al      ; set # of units
```
In case of no floppy, it returns 0 units from
blk dev, no no units are allocated for floppies,
and as the result, hd driver allocates from `A:`.
In which case it should boot properly from
`A:` as if it was HD. So what exactly was the
problem when it was accessing A? Maybe it
was all on purpose?

**Comment by andrewbird** [comment] 2017-10-25 22:25
So, using the boot.blk from the hdimage (I have to assume it's okay) and `$_floppy_a = ""` it doesn't seem to want to access command.com on DISK 80
![pcmos-no-floppy-with-bootblk](https://user-images.githubusercontent.com/220835/32025780-587752ca-b9d9-11e7-9d5c-0713bcdde257.png)
Log finishes here
~~~
fatfs: reading cluster 34 (+0)                                                  
fatfs: cluster 34 is in object 2                                                
fatfs: read_file: obj 2, cluster 34, sec 0                                      
fatfs: going to read 0x200 bytes from file "/clients/common/dosemu2.git/test-imagedir/dXXXXs/mos/$$shell.sys", ofs 0x0
DISK read @2/4/16 (1) -> 0x2e9c0 OK. 
~~~

if I set `$_floppy_a = "a.img"` which is a dd from /dev/zero 360k not formatted
![pcmos-unformatted-floppy-with-bootblk](https://user-images.githubusercontent.com/220835/32025955-01e07850-b9da-11e7-9fd9-be4101815650.png)

Only with the unformatted floppy image configured does it continue
~~~                                    
INT13: ax=0201 cx=0408 dx=0380                                                  
DISK 80 read [h:3,s:7,t:4](1)->2e1c:0000                                        
DISK: /clients/common/dosemu2.git/test-imagedir/dXXXXs/mos: Trying to read 1 sectors at LBA 330+0 at pos 160256
fatfs: read: dir /clients/common/dosemu2.git/test-imagedir/dXXXXs/mos, sec 313, len 1
fatfs: dir /clients/common/dosemu2.git/test-imagedir/dXXXXs/mos, reading data sector 264
fatfs: reading cluster 35 (+0)                                                  
fatfs: cluster 35 is in object 3                                                
fatfs: read_file: obj 3, cluster 35, sec 0                                      
fatfs: going to read 0x200 bytes from file "/clients/common/dosemu2.git/test-imagedir/dXXXXs/mos/command.com", ofs 0x0
DISK read @3/4/7 (1) -> 0x2e1c0 OK.                                             
INT13: ax=0201 cx=0002 dx=0180                                                  
DISK 80 read [h:1,s:1,t:0](1)->2d9c:0000                                        
DISK: /clients/common/dosemu2.git/test-imagedir/dXXXXs/mos: Trying to read 1 sectors at LBA 18+0 at pos 512
fatfs: read: dir /clients/common/dosemu2.git/test-imagedir/dXXXXs/mos, sec 1, len 1
fatfs: dir /clients/common/dosemu2.git/test-imagedir/dXXXXs/mos, reading fat sector 0
~~~

**Comment by stsp** [comment] 2017-10-26 01:14
Perhaps the test on pcem would be good then. :)

**Comment by dcoshea** [comment] 2017-10-26 09:21
> Could you possibly explain why the OS that
> is claimed to be 386-specific and to use MMU,
> works under dosemu2 at all? It shouldn't! :)

No, sorry, I actually know very little about PC-MOS outside of building it!

**Comment by andrewbird** [comment] 2017-10-26 11:12
I didn't try PCEM yet, as I'm still sniffing around the source.
It seems _NETBIOS.ASM has some minimal int 2f stuff, just 2f/b7 APPEND and 2f/b8 NETWORK. I wasn't aware of those functions.

**Comment by stsp** [comment] 2017-10-26 11:26
@dcoshea Have you successfully built it?
I tried with bc-3.1 and getting this:
```
make -f kernel.mak $$eval.sys
MAKE Version 3.6  Copyright (c) 1991 Borland International

Available memory 516704 bytes

Fatal: '$$eval.sys' does not exist - don't know how to make it
```

It seems borland's make does non understand
the `$$$$eval.sys` stuff.

@andrewbird _NETBIOS.ASM seems to only provide
the handler for int2f's subfunctions, but this is not
what we are looking for. It should _call out_ the
external redirector, meaning that there should be
`int 2fh` calls that are not handled by mos itself.
And I fail to find even a single `int 2fh` call.

**Comment by stsp** [comment] 2017-10-26 11:34
Hmm, these `make` problems all look
trivially fixable, so maybe I'll build it. :)

**Comment by andrewbird** [comment] 2017-10-26 11:49
Yes it would nice to know the source matches the code i'm trying to run/debug, maybe even get a symbol file.

**Comment by andrewbird** [comment] 2017-10-26 12:16
Just in case you want to try out your build on dosemu, here's my wip patch (MFS disabled) [mos.zip](https://github.com/stsp/dosemu2/files/1418283/mos.zip)

**Comment by andrewbird** [comment] 2017-10-26 12:25
FYI their cddriver CDLINK installs a device driver that is an int21 frontend (like Netware used to be). So the redirector is not required, at least for that. It creates a non-IBM block device to create the drive so it doesn't manipulate CDS for that either.

**Comment by stsp** [comment] 2017-10-26 13:59
> Just in case you want to try out your build on dosemu, here's my wip patch (MFS disabled) mos.zip

I would very much be interested to try
my build on dosemu, but so far it does
not exist, plus I keep having problems
setting up the build environment with
dosemu2. Yesterday I did the necessary
system.com fixes and got a bit further,
but now I am hitting #505 because my
toolchain was set up with russian/cyrillic
DOS, and now I don't see what errors
it writes to me. Being unable to set up
a compiler toolchain makes me angry,
as it is one of the primary targets for
dosemu2, and it still fails. :(

> FYI their cddriver CDLINK installs a device driver
> that is an int21 frontend (like Netware used to be).
> So the redirector is not required, at least for that.

You are probably saying this as an evidence
that they lack a redirector support. So quite bad.
In either case, I don't think we can go anywhere
beyond just running pcmos along with many other
DOSes we support. Even if you compile it with a
GPLed toolchain, I don't share your view on what
can be got from that: we can't make just some
DOS to be our primary target, unless it has a
nearly 100% compatibility with MS-DOS, and,
preferably, is written in C so that we can fix it
ourselves when bugs are reported.

**Comment by andrewbird** [comment] 2017-10-26 15:13
To be honest, just getting it running was my primary target. Not sure what I'd use it for myself.

I turned on all the debug flags and see a little more. It seems it really is trying to open C:\COMMAND.COM, I wonder why that fails
Bad log
~~~
INT21 (1) at fc00:01e9: AX=3d00, BX=8bac, CX=ffff, DX=02d3, DS=0070, ES=0190    
INT21: open file "C:\COMMAND.COM"                                               
int 0x21, ax=0x3d00                                                             
HLT: fcn 0x01e9 called in HLT block, handler: ints thread non-revect +0xe6      
HLT: fcn 0x0102 called in HLT block, handler: int return +0                     
21 > f8                                                                         
21 > f8                                                                         
~~~

Good log
~~~
INT21 (1) at fc00:01e9: AX=3d00, BX=8bac, CX=ffff, DX=02d3, DS=0070, ES=0190    
INT21: open file "C:\COMMAND.COM"                                               
int 0x21, ax=0x3d00                                                             
HLT: fcn 0x01e9 called in HLT block, handler: ints thread non-revect +0xe6      
HLT: fcn 0x0102 called in HLT block, handler: int return +0                     
21 > f8                                                                         
21 > f8                                                                         
fake_int: CS:IP 76f1:e4ec                                                       
int 0xe6, ax=0x2142                                                             
HLT: fcn 0x00e8 called in HLT block, handler: interrupts +0xe6                  
HLT: fcn 0x01e9 called in HLT block, handler: ints thread non-revect +0xe6      
INT21 (1) at fc00:01e9: AX=3e05, BX=0005, CX=ffff, DX=02d3, DS=0070, ES=0190    
int 0x21, ax=0x3e05                                                             
HLT: fcn 0x01e9 called in HLT block, handler: ints thread non-revect +0xe6      
HLT: fcn 0x0102 called in HLT block, handler: int return +0                     
21 > f8                                                                         
21 > f8                                                                         
HLT: fcn 0x0012 called in HLT block, handler: interrupts +0x10                  
HLT: fcn 0x0113 called in HLT block, handler: ints thread non-revect +0x10      
INT10: get ega info: bx 0x0003, cx 0x0f09                                       
HLT: fcn 0x0113 called in HLT block, handler: ints thread non-revect +0x10      
HLT: fcn 0x0102 called in HLT block, handler: int return +0                     
HLT: fcn 0x0012 called in HLT block, handler: interrupts +0x10                  
HLT: fcn 0x0113 called in HLT block, handler: ints thread non-revect +0x10      
INT10: disable cpu access to video (ignored)                                    
HLT: fcn 0x0113 called in HLT block, handler: ints thread non-revect +0x10      
HLT: fcn 0x0102 called in HLT block, handler: int return +0                     
HLT: fcn 0x0012 called in HLT block, handler: interrupts +0x10                  
HLT: fcn 0x0113 called in HLT block, handler: ints thread non-revect +0x10      
INT10: get cursor pos: page 0, x.y 0.10, shape 6-7                              
HLT: fcn 0x0113 called in HLT block, handler: ints thread non-revect +0x10      
HLT: fcn 0x0102 called in HLT block, handler: int return +0                     
HLT: fcn 0x0012 called in HLT block, handler: interrupts +0x10                  
HLT: fcn 0x0113 called in HLT block, handler: ints thread non-revect +0x10      
INT10: get video mode: mode 0x03, page 0, 80 colums                             
HLT: fcn 0x0113 called in HLT block, handler: ints thread non-revect +0x10      
HLT: fcn 0x0102 called in HLT block, handler: int return +0                     
fake_int: CS:IP 76f1:ecbf                                                       
int 0xe6, ax=0x2142                                                             
HLT: fcn 0x00e8 called in HLT block, handler: interrupts +0xe6                  
HLT: fcn 0x01e9 called in HLT block, handler: ints thread non-revect +0xe6      
INT21 (1) at fc00:01e9: AX=4b01, BX=e464, CX=0190, DX=02d3, DS=0070, ES=76f1    
INT21 4B: load/execute program="C:\COMMAND.COM", L(cmdline=" /p")=3             
int 0x21, ax=0x4b01                                                             
HLT: fcn 0x01e9 called in HLT block, handler: ints thread non-revect +0xe6      
HLT: fcn 0x0102 called in HLT block, handler: int return +0                     
3d4 < e                                                                         
3d5 < 3                                                                         
3d4 < f                                                                         
3d5 < 20                                                                        
HLT: fcn 0x0015 called in HLT block, handler: interrupts +0x13                  
HLT: fcn 0x0116 called in HLT block, handler: ints thread non-revect +0x13      
INT13: ax=0201 cx=0408 dx=0380                                                  
DISK 80 read [h:3,s:7,t:4](1)->2e1c:0000                                        
DISK: /clients/common/dosemu2.git/test-imagedir/dXXXXs/mos: Trying to read 1 sectors at LBA 330+0 at pos 160256
fatfs: read: dir /clients/common/dosemu2.git/test-imagedir/dXXXXs/mos, sec 313, len 1
fatfs: dir /clients/common/dosemu2.git/test-imagedir/dXXXXs/mos, reading data sector 264
fatfs: reading cluster 35 (+0)                                                  
~~~

**Comment by stsp** [comment] 2017-10-26 16:28
You probably already see that the
first log is a subset of the second one.
So if it locks up, maybe it would be
possible with dosdebug to see where?

**Comment by andrewbird** [comment] 2017-10-26 17:29
INT21/3d returns CARRY / AX=03 "path not found" (that aligns with what we see in the log). Just tried to 'bpint 21, then ti ...' but end up with GPF
Trace file [fail3.zip](https://github.com/stsp/dosemu2/files/1419398/fail3.zip)

**Comment by stsp** [comment] 2017-10-26 17:50
This is not a dosemu log.

**Comment by stsp** [comment] 2017-10-27 01:40
It is now possible to set up the build
environment under DOS, and then under
linux you can go to `pcmos386v501/SOURCES/src`
and do:
`dosemu -td -E MAKEMOS.BAT`

**Comment by dcoshea** [comment] 2017-10-27 07:07
@stsp

> Have you successfully built it?

Yes, but still haven't tried under dosemu2, sorry!  Also there is a caveat here: I don't know if I have built *all* the artefacts.

> make -f kernel.mak $$eval.sys

Were you running that directly or via `MAKEMOS.BAT`?  I tried to stick to running `MAKEMOS.BAT`, I think.  Also, I noticed that `MAKEMOS.BAT` wasn't actually using Borland C++ to build things by default (unless you modify some of the C sources or remove some objects; as I mentioned in one of the issues on the project, there's no `make clean` equivalent), so I didn't necessarily install Borland C++ in every development environment I tried, so the build might have used `/BIN/MAKE.EXE` (which isn't Borland) instead.

**Comment by andrewbird** [comment] 2017-10-27 10:20
Here's a patch for mhp logging / pcmos support, and a log file from a debugging run. 'bpint 21; g; ti; ti ...'.
It has the same result though GPF.
[t4.zip](https://github.com/stsp/dosemu2/files/1421700/t4.zip)

**Comment by stsp** [comment] 2017-10-27 11:03
@dcoshea Yes, its likely targeted to
different, non-borland make, or perhaps
more recent one that I have. If time
permits, I'll fix things up to work with
a genuine borland make - the problems
look all trivial, it took much more time
to fix dosemu2 to get this working.

@andrewbird Try disabling int21 revectoring
in can_revector() and disable dos_post_boot().
Maybe revectoring does not live well with
dosdebug.

**Comment by stsp** [comment] 2017-10-27 12:29
Borland toolset is completely hopeless,
so I'll integrate the support for masm
toolset into dosemu2 (pcmos already
provides the toolset but dosemu2 does
not allow to automate the build process
right now - it should!)

**Comment by andrewbird** [comment] 2017-10-27 22:23
Thanks, disabling the revectoring of int21 allowed dosdebug to get a lot further. I've attached new logs, and the corresponding patch for you to look at. The logs seem to diverge after getting a different value from 'IN AL, 21'  and testing bit one 'test AL, 01' which I believe is an interrupt controller port. I may be wrong on that, as you can imagine how many FTP hits Google has for 'PORT 21' ?
The zip is here [t5.zip](https://github.com/stsp/dosemu2/files/1423603/t5.zip)

Significant lines are (referencing t5-bad.log)
38872 Start of interrupt handler
40842 IN AL,21
59377 STC
59408 MOV AX, 0003 (Path not found error)

**Comment by jschwartzenberg** [comment] 2017-10-28 11:13
What are the problems with the Borland toolset? I was thinking of scripting its installation.

**Comment by stsp** [comment] 2017-10-28 17:22
> Thanks, disabling the revectoring of int21 allowed dosdebug to get a lot further.

OK, please fill in a bug report then
(and perhaps also a PR fix :)

> I may be wrong on that, as you can imagine how many FTP hits Google has for 'PORT 21' ?

Please use `PORTS.*` files from RBIL.
But you are not wrong, port 21h is an
interrupt controller mask register. So
if someone tests bit 1, he probably is
looking whether the timer IRQ is masked.
Which, of course, makes no sense. :)
But if you look into the sources:
```
; the following test to see if application has mask out irq 0's
; and called a function which will enventualy call tsl which will
; switch task and because irq 0 is disable we will no be able to
; get control and thus we will be stuck in the other task.  if
; application does this we can logically assume that this app
; should not spend much time in this state.

        in      al,21h
        test    al,1                    ; check irq 0
        jnz     tsl041
```

So it seems there is a convention in MOS that
when timer irq is masked, the in-kernel preemption
does not happen (aka preempt_disable() in linux).
For debugging you should probably indeed mask
IRQ0 then so to not trace into a preemption code
path.

**Comment by stsp** [comment] 2017-10-28 17:24
> What are the problems with the Borland toolset? I was thinking of scripting its installation.

For example google for `Fatal: Command arguments too long`
from borland's make. It seems to be still unfixed,
20+ years later. I am hitting it during compilation
of MOS. In any case, MOS provides MS toolchain,
so I only need to tweak dosemu to get the
automation in.

**Comment by andrewbird** [comment] 2017-10-28 17:51
`Fatal: Command arguments too long` - this [thread](https://groups.google.com/forum/#!topic/borland.public.cppbuilder.commandlinetools/t0aQTY9fH34) suggests it may be the length of the PATH variable that's causing the problem.

**Comment by stsp** [comment] 2017-10-28 17:57
But its not, I checked that it is exactly
the command line passed to the make
itself.

**Comment by andrewbird** [comment] 2017-10-28 23:44
Getting a little further. I managed to match the source code to the trace logging, just manually though. Anyway it seems that the int21/3d open handler checks to see if the path is valid and tries to match the drive in linked list of 'BDB' structures.
In the bad case there's just one entry(correct), but its drive field is set to '00' i.e. drive 'A'.
In the good case there are 3 entries, with drives '00', '01' and '02'

Next pointer is at +0x8
Drive number is at +0x10
~~~
============ bad                                                                
                                                                                
d 1bb5:0000                                                                     
                                                                                
1bb5:0000 48 42 06 00 BB 1B AD 1B 00 00 00 00 B5 1B 00 00  HB..;.-.....5...     
1bb5:0010 00 00 00 02 07 03 01 00 02 00 02 31 00 21 0A 08  ...........1.!..     
1bb5:0020 00 11 00 D2 24 18 0C F8 00 FF FF FF FF 01 00 FF  ...R$.               
1bb5:0030 FF 4E 00 08 22 0A 00 00 00 00 00 00 00 04 00 70 N.."..........p       
1bb5:0040 00 32 01 00 00 44 00 11 00 11 00 00 00 FF 37 51  .2...D......7Q       
1bb5:0050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
1bb5:0060 48 43 06 00 C1 1B B5 1B 00 00 00 00 90 01 00 00  HC..A.5.........     
1bb5:0070 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
                                                                                
============ good                                                               
                                                                                
1bad:0000 48 42 06 00 B3 1B 8C 1B B9 1B 00 00 AD 1B 00 00  HB..3...9...-...     
1bad:0010 00 00 00 02 00 00 01 00 02 E0 00 21 00 20 0B 09  .........`.!. ..     
1bad:0020 00 13 00 34 19 18 0C F0 00 10 00 B9 1B 01 00 FF  ...4...p...9..       
1bad:0030 FF 4E 00 01 21 0B 00 00 00 00 00 00 00 04 00 FF N..!.........         
1bad:0040 FF 00 00 00 00 24 00 12 00 00 00 00 00 00 40 0B ....$........@.       
1bad:0050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
1bad:0060 48 43 06 00 B9 1B AD 1B BF 1B 00 00 90 01 00 00  HC..9.-.?.......     
1bad:0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
                                                                                
d 1bb9:0000                                                                     
                                                                                
1bb9:0000 48 42 06 00 BF 1B B3 1B CD 1B AD 1B B9 1B 00 00  HB..?.3.M.-.9...     
1bb9:0010 01 01 00 02 00 00 01 00 02 E0 00 21 00 20 0B 09  .........`.!. ..     
1bb9:0020 00 13 00 34 19 18 0C F0 00 10 00 CD 1B 01 00 FF  ...4...p...M..       
1bb9:0030 FF 4E 00 01 21 0B 00 00 00 00 00 00 00 04 00 FF N..!.........         
1bb9:0040 FF 00 00 00 00 24 00 12 00 00 00 00 00 00 40 0B ....$........@.       
1bb9:0050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
1bb9:0060 48 43 06 00 C5 1B B9 1B D3 1B B3 1B 90 01 00 00  HC..E.9.S.3.....     
1bb9:0070 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
                                                                                
d 1bcd:0000                                                                     
                                                                                
1bcd:0000 48 42 06 00 D3 1B C5 1B 00 00 B9 1B CD 1B 00 00  HB..S.E...9.M...     
1bcd:0010 02 00 00 02 07 03 01 00 02 00 02 31 00 21 0A 08  ...........1.!..     
1bcd:0020 00 11 00 D2 24 18 0C F8 00 FF FF FF FF 01 00 FF  ...R$.               
1bcd:0030 FF 4E 00 08 22 0A 00 00 00 00 00 00 00 04 00 70 N.."..........p       
1bcd:0040 00 32 01 00 00 44 00 11 00 11 00 00 00 FF 37 51  .2...D......7Q       
1bcd:0050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
1bcd:0060 48 43 06 00 D9 1B CD 1B 00 00 BF 1B 90 01 00 00  HC..Y.M...?.....     
1bcd:0070 02 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
~~~

So as we might have expected the issue is that somehow our C: drive is being marked as drive 'A'. Tomorrow i'll look into where the BDBs get written. Now it'd be really nice if dosdebug could set a breakpoint on specific memory write....

**Comment by stsp** [comment] 2017-10-29 00:03
But I already quoted where _exactly_
does this happen:
```
fini10:
        mov     bx,[hdr]
        inc     al                      ; maximum drive number --> # of units
        mov     es:[bx].irUnits,al      ; set # of units
```

Find this place and with a few context
you'll see we are setting irUnits to 0 if
there are no floppies, and to 2 if there
are at least 1 floppy. The question is
only why A: doesn't work as HDD - it
should. Renaming to A seems to be on
purpose (a very strange purpose, but
it is).

> Now it'd be really nice if dosdebug could set a breakpoint on specific memory write....

This is quite difficult to code in dosdebug,
but you can mix dosdebug and gdb. I
regularly do that exactly to set up memory
watch points.

**Comment by andrewbird** [comment] 2017-10-29 09:25
Boot drive number is passed in the boot block at offfset 0x3e, which explains the disparity from that snippet of code. I know in my patch I'm fixing it up to be boot drive(02) in update_geometry() / read_boot(), but even if I don't then in the case of using my boot.blk file it will still be 02 since it was created when a floppy was present.

So it would seem that in a real system if it were installed from floppy to hard disk, then the floppy disks were disabled in the bios it would have the same problem. Perhaps that's a corner case and hard disks without floppies are A: under PC-MOS? I really need to find some PC-MOS user / installation manual, but no luck so far.

**Comment by stsp** [comment] 2017-10-29 14:19
But have you find a workable solution,
like passing the boot drive as A and yet
load a system files from C or something
like this?

**Comment by stsp** [comment] 2017-10-29 15:04
I think it should be always set to 0x80,
it will just be referenced as 'A' later.
How about just passing `A:\COMMAND.COM`
via `shell=` in config.sys?

**Comment by andrewbird** [comment] 2017-10-29 15:19
I thought that `shell=a:\command.com` would work, but apparently not.
![pcmos-shell-a-config_sys](https://user-images.githubusercontent.com/220835/32145201-6dcefcbe-bcbc-11e7-9e11-33711aea3484.png)

**Comment by stsp** [comment] 2017-10-29 15:29
Looks like parse error, maybe you
forgot DOSish CRLFs at the end?

**Comment by andrewbird** [comment] 2017-10-29 16:08
I did do unix2dos on it beforehand and just to check I deleted/recreated/unix2dos again with same result.

**Comment by stsp** [comment] 2017-10-29 16:26
But can it be that buggy as to corrupt
its memory on any unknown config.sys
command? :(

**Comment by andrewbird** [comment] 2017-10-29 17:17
So I just installed a fresh type1 hdimage using the SHIPMOS/1_MOS5userSystemSN0530041410.zip which has an install program. Firstly you have to set the date back (I used 1993) else hdsetup can't read a file it creates itself. After installation, I first booted from C: with floppy A: configured - okay. Then I disabled the floppy and again tried booting from C: but I get the now familiar 'Internal error # Command processor cannot be found' message. So as far I'm concerned it seems I'm trying to fix an issue within Dosemu that's actually an issue with PC-MOS on native hardware.
I see two ways forward:
- forget about PC-MOS, given this issue, 2012 date issue and its lack of redirector support.
- tidy up and commit what I have, but warn if no floppies configured that drive assignment is wrong.

What do you think?

**Comment by stsp** [comment] 2017-10-29 17:22
I think it would be good to add any possible
support, because MOS problems may be fixed.
For example to work around the drive problem
it may be enough to always write 2 to irUnits.

**Comment by jschwartzenberg** [comment] 2017-10-29 17:23
The bugs in PC-MOS could be reported in their GitHub issue tracker.

**Comment by stsp** [comment] 2017-10-29 17:26
@jschwartzenberg Its a chicken-and-egg problem:
if we don't add some support, there is nothing to
report to MOS. But if we do, then it doesn't work,
and as far as it does not, no one is likely to look
into such reports. Still it may be better than nothing.

**Comment by andrewbird** [comment] 2017-10-30 18:53
Just a quick note in case anyone needs it, do be very careful about all the files dates on the filesystem. I found that whilst testing emufs.sys that both it and config.sys needed old file dates or the boot would hang.

**Comment by dcoshea** [comment] 2017-11-04 02:45
> For example google for Fatal: Command arguments too long
> from borland's make. It seems to be still unfixed,
> 20+ years later. I am hitting it during compilation
> of MOS.

@stsp I don't recall seeing this.  Are you using exactly the directory layout that `MAKEMOS.BAT specifies, i.e. with most things directly under the root directory?  I'm just wondering if moving things down a directory level would make paths longer and cause problems here.

Of course, another possible reason I didn't see it is perhaps I didn't rebuild the same things as you!

**Comment by stsp** [comment] 2017-11-04 09:04
No, we were talking about borland make.
Its not the same as the Microsoft toolset
that comes with MOS and you used.
I am currently adapting dosemu2 to automate
the build with this Microsoft toolset, and
borland toolset is hopeless.

**Comment by stsp** [comment] 2017-11-05 02:00
I submitted the PR that automates the build under dosemu2:
https://github.com/roelandjansen/pcmos386v501/pull/22
And a fix for floppy crash:
https://github.com/roelandjansen/pcmos386v501/pull/23
@andrewbird Could you please fix that everything
works as expected?
For me it works only with kvm but not with cpuemu
(neither jit nor sim).

**Comment by andrewbird** [comment] 2017-11-05 11:31
@stsp It might be a few days before I can check this out, my desktop PC just died...

**Comment by stsp** [comment] 2017-11-05 13:20
> @stsp It might be a few days before I can check this out, my desktop PC just died...

And not for the first time, IIRC. :)
Good luck with repairing, I already know
that desktops (in my case AMD-based ones)
sometimes fall into an infinite recursion
of the break/repair cycles.

**Closed** 2017-11-07 11:46 UTC

**Comment by stsp** [comment] 2017-11-07 11:47
I added the hack to set boot drive to 0 for MOS.
It now boots properly and starts enumerating HDDs
from A (seems to be intentional in its code).

**Comment by andrewbird** [comment] 2017-11-20 10:10
After your changes to PC-MOS to correct the boot drive number with no floppy, will it be necessary to change dosemu boot to cope with the now correct behaviour? If so, I wonder if we can change some version string in PC-MOS so we can easily identify old and new variants of v5.01. I suppose I should also test the earlier versions of PC-MOS on winworld to see how they behave.

**Comment by stsp** [comment] 2017-11-20 14:16
Can't check right now but I think so.
In either case, we are safe unless
there is some MOS _release_, rather
than the git patch. I hope they will
add the new strings when doing a
release.
Overall I don't see a big need in supporting
MOS forever. It is quite buggy and especially
difficult to change: define a new variable in
some ".inc" header, and it falls apart for no
obvious reasons. Set proper date of
`$$shell.sys`, and it falls apart. The main
need of supporting it is only because it shows
many weaknesses in dosemu2 itself.

Now you can just test it for yourself: grab
my build patch from their git, and it builds
with just starting `./build.sh`
