### ISSUE TITLE
move installation to xxx/dosemu2?

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#903] opened 2019-08-12 13:23 UTC
This is a question mostly for people that
do packaging of dosemu1/2 for distros.
Should I finally rename the install pathes
and the binaries to allow the parallel install
of dosemu1 and 2? They are now hell
incompatible, so I plan to use ~/.dosemu2
already anyway. And I can do things for
dosemu2 to ignore the dosemu-freedos
installs, so that it can work on top of the
dosemu1 installs and still use fdpp, so I
see no urgent need to also rename binaries.
But at that point it may just be worth doing.
Will that help?

**Comment by jschwartzenberg** [comment] 2019-08-12 18:57
Nobody is going to maintain dosemu1 or be interested in it. I'm quite sure distro packagers will be happy to toss out the unmaintained dosemu1 and put dosemu2 in its place.

**Comment by stsp** [comment] 2019-08-12 19:26
Debian still maintains dosemu1, believe it or not.

**Comment by andrewbird** [comment] 2019-08-12 19:42
Do they, when did they last patch it?

**Comment by jschwartzenberg** [comment] 2019-08-12 19:56
There are two open bugs here:
https://bugs.debian.org/cgi-bin/pkgreport.cgi?tag=help&pend-exc=pending-fixed&pend-exc=fixed&pend-exc=done&src=dosemu

**Comment by jschwartzenberg** [comment] 2019-08-12 20:02
@kees I see you're maintaining Debian's dosemu package. How do you see its feature with respect to this ticket? I think for all intents and purposes DOSEMU2 had better replace DOSEMU1.

**Comment by jschwartzenberg** [comment] 2019-08-12 20:33
@bartoldeman I see the DOSEMU SF page which also hosts dosemu.org is associated to you. What do you think packagers should do with DOSEMU1 and DOSEMU2?

As long as the original DOSEMU site exists without a pointer to DOSEMU2, there will be people trying it before finding/trying DOSEMU2.

**Comment by stsp** [comment] 2019-08-12 20:38
> As long as the original DOSEMU site exists without a pointer to DOSEMU2,
> there will be people trying it before finding/trying DOSEMU2.

This is fine for as long as dosemu2 was never released.
And no one knows if it will. :)

**Comment by andrewbird** [comment] 2019-08-12 21:24
@jschwartzenberg yes but two open bugs from 2008/2007 and no replies or fixes does not count as maintaining it. In my book, that's just withering on the vine, nobody has even bothered to cull it.
Ubuntu is not much better, https://bugs.launchpad.net/ubuntu/+source/dosemu/+bugs?orderby=-id&start=0 shows that just one bug reported since 2012 and it has no replies other than a 'me too'.

Doesn't look like either are being maintained to me.

**Comment by stsp** [comment] 2019-08-12 23:08
Well, these links show lots of bugs,
and perhaps only the open ones?

**Comment by andrewbird** [comment] 2019-08-13 08:40
> Well, these links show lots of bugs,
and perhaps only the open ones?

Fair point, so in Ubuntu I tweaked the filters to include all closed bugs, ordered them by bug number, and found that the latest bug marked fix-released was in 2009 and was an Upstream sync. I tried to do a similar thing in the Debian tracker, but it yielded no more results than the two linked above.

**Comment by stsp** [comment] 2019-08-13 09:18
Then what Kees is up to?
Is he not interested in dosemu
overall (and will eventually drop
dosemu1 too), or only in dosemu2?

As for whether dosemu2 can pick
up the user's setup, is the main question.
It can in most cases, and certainly
does for a default case. But the
heavily tweaked setups may not be
picked up correctly. Plus taking up
the old setup limits the user to the
DOS he used, which is in most cases
freedos from dosemu-freedos pack.
We want to provide a better DOS than
the one used by default in dosemu1.
So the question is really not that simple.

**Comment by andrewbird** [comment] 2019-08-13 09:43
I think if `kernel.sys` is present in the user's drive_c then dosemu2 has to respect that; if dosemu2 uses that to boot and the user notices no difference I'd call that a success!

**Comment by andrewbird** [comment] 2019-08-13 09:46
And as for old freedos default setup (I presume that's the magic that uses the system installed `kernel.sys` to boot), ignoring it and then looking in drive_c, finding nothing and failing over to FDPP also sounds like a good scenario.

**Comment by skitt** [comment] 2019-08-13 09:53
> And as for old freedos default setup (I presume that's the magic that uses the system installed `kernel.sys` to boot), ignoring it and then looking in drive_c, finding nothing and failing over to FDPP also sounds like a good scenario.

Yes, that does sound like a good scenario.

There’s always the option of documenting the issues, without handling everything in code, and letting package maintainers fill in the gaps as appropriate. (Don’t get me wrong, I for one certainly appreciate that you’re even thinking of this stuff; and IMO it’s better to handle things upstream rather than have every distribution duplicate bits of scripts. But there’s always a balance...)

**Comment by andrewbird** [comment] 2019-08-13 10:10
@skitt a little off topic, but very important for us, would you consider packaging the [djgpp](http://www.delorie.com/djgpp/) DOS cross-compiler for Debian / Ubuntu? It's the last piece in the puzzle for getting a fully transparent source to binary path for many DOS apps.

**Comment by stsp** [comment] 2019-08-13 10:11
If I am not mistaken, dosemu1 used
to copy or symlink kernel.sys to C, so
that solution won't work. Please
refresh my memory if I am wrong.

**Comment by andrewbird** [comment] 2019-08-13 10:17
I suppose we could ignore the user's drive_c/`kernel.sys` if it's a symlink to system installed one, but then I suppose that leaves us with the question of what to do with his potentially modified `config.sys` and `autoexec.bat`. Sounds like time to issue a warning, but honour all files in the drive_c.

**Comment by skitt** [comment] 2019-08-13 10:20
> @skitt a little off topic, but very important for us, would you consider packaging the [djgpp](http://www.delorie.com/djgpp/) DOS cross-compiler for Debian / Ubuntu? It's the last piece in the puzzle for getting a fully transparent source to binary path for many DOS apps.

Heh, funnily enough...

```
$ dpkg -l | grep djgpp
ii  binutils-djgpp                              2.25.1-3+5.2                                            amd64        Cross-binutils for DOS using DJGPP
ii  gcc-djgpp-bootstrap                         4.9.3-4+15.1                                            amd64        GNU Compiler Collection for MinGW-w64
```

I’m working on it ;-).

**Comment by andrewbird** [comment] 2019-08-13 10:20
Oh cool, that makes me **very** happy!

**Comment by stsp** [comment] 2019-08-13 10:29
@skitt are you aware of @jwt27 djgpp
efforts? Would be nice if you reuse his
work. Also I tried him as an upstream
for djgpp patches, but they are still in
unapplied PRs there.

**Comment by stsp** [comment] 2019-08-13 10:32
@andrewbird I can't honour all config
files if I ignored kernel.sys, because it
is exactly kernel.sys who honours them.
I think there is already a warning about
an orphaned config.sys, but we need
much more warnings of that kind.

**Comment by andrewbird** [comment] 2019-08-13 10:49
@stsp Yep, I agree, I just didn't phrase it very well, I'll try again. I think that if `kernel.sys` exists as either symlink or file in drive_c we have to honour them, but if it's a symlink to the system installed one we could issue a warning in addition.
On the subject of FDPP messages, this message from the plugin needs the 'ERROR' to be toned down to 'INFO' or suchlike: `ERROR: fdpp booting, this is very experimental!`

**Comment by skitt** [comment] 2019-08-13 12:59
> @skitt are you aware of @jwt27 djgpp efforts? Would be nice if you reuse his work. Also I tried him as an upstream for djgpp patches, but they are still in unapplied PRs there.

I am indeed; I try to keep an eye on all such packaging efforts. There’s not necessarily all that much that can be reused in the main build scripts for a distribution such as Debian, but it’s always useful to look at configure options and patch collections, and it helps to avoid creating arbitrarily-incompatible packages...

**Comment by stsp** [comment] 2019-08-13 16:06
Great, so in this case I'd just mention the patch
I'd like to get included:
http://www.delorie.com/djgpp/mail-archives/browse.cgi?p=djgpp/2019/08/11/08:29:33
And is also here:
https://github.com/jwt27/djgpp-cvs/pull/1

Since I can't find any potential upstream, lets
assume you (@skitt) can be the one. :)

**Comment by stsp** [comment] 2019-08-13 16:08
> On the subject of FDPP messages, this message from the plugin needs the 'ERROR' 

Feel free to submit a patch.
To downgrade the message, you need to prefix
it with the `@` sign.

**Comment by skitt** [comment] 2019-08-13 16:37
> Great, so in this case I'd just mention the patch
> I'd like to get included:
> http://www.delorie.com/djgpp/mail-archives/browse.cgi?p=djgpp/2019/08/11/08:29:33
> And is also here:
> [jwt27/djgpp-cvs#1](https://github.com/jwt27/djgpp-cvs/pull/1)
> 
> Since I can't find any potential upstream, lets
> assume you (@skitt) can be the one. :)

Duly noted, I’ll add it as a patch to the Debian packaging. I can also ping DJ in a couple of weeks if there hasn’t been any reaction!

**Comment by stsp** [comment] 2019-08-13 16:52
If you have any contacts with him - why not!
I think he is also a github user here:
https://github.com/djdelorie

**Comment by jschwartzenberg** [comment] 2019-08-13 19:47
The trick seems to be just mentioning people like this @djdelorie :)

**Comment by djdelorie** [comment] 2019-08-13 19:56
Really, if you can't figure out how to get in touch with *me*, you aren't even trying... ;-)

**Comment by stsp** [comment] 2019-08-13 20:40
:)
But I tried via ML.
http://www.delorie.com/djgpp/mail-archives/browse.cgi?p=djgpp/2019/08/11/08:29:33

**Comment by djdelorie** [comment] 2019-08-13 20:45
Yup, saw it.  I sent a note to Juan asking if he had time to look at it; he does pretty much all the djgpp library work these days.  The real catch with this patch is that the stub is compiled in to all executables; patching the dev kit won't fix existing binaries.

**Comment by stsp** [comment] 2019-08-13 20:49
Yep, I noticed that even the "strip" tool needs
to be replaced with that patch applied. I would
suspect it just checks the stub for an exact
match before processing - maybe such a check
can be relaxed?
Other than that, I replaced "stubify" and things
seem to work well.

**Comment by djdelorie** [comment] 2019-08-13 20:57
yeah, binutils has a built-in copy of the stub it uses for linking etc (there are environment variables to override) but the stub "detection" is just the MZ bytes plus a COFF header at offset 2048
The biggest challenge to editing the stub is keeping it 2048 bytes or less :-)

**Comment by stsp** [comment] 2019-08-15 13:27
By the way, @djdelorie, don't take this as a
trolling or an attempt to tell you what to do -
I know your development practices with djgpp
are established now for many decades, but
have you ever considered moving the development
to github, or at least create the mirror here?
Otherwise other people have to do that:
https://github.com/jwt27/djgpp-cvs
Then the development is much more open
for community.

**Comment by djdelorie** [comment] 2019-08-15 18:35
Well, we have a public mailing list and a public source repo.  Development of djgpp is very slow these days, mostly it's just rebuilding new upstream packages as they're released.  The amount of effort to move or mirror anything is way more than the amount of development effort happening at the moment.  Plus, I'm not a fan of git.  We've been using CVS for 30 years now, we're kinda used to it.

**Closed** 2019-08-15 23:18 UTC

**Comment by stsp** [comment] 2019-08-16 11:47
> but the stub "detection" is just the MZ bytes plus a COFF header at offset 2048

@djdelorie But if you only compare MZ bytes
and a COFF header, then am I right that the
tools like "strip" should still work, even after
the stup is changed, provided that it didn't
exceed 2048 bytes? But this is not what I see.
With my patch applied, old "strip" complains,
so it needs to be re-built (which is what I
didn't do).

**Comment by jschwartzenberg** [comment] 2019-08-17 17:20
While the Stretch/Sid package of dosemu1 works fine in Buster, the current version of Debian, Buster, was released without dosemu.

**Comment by stsp** [comment] 2019-08-17 17:28
I can't speak for Kees or dosemu1 devs.
The best we can do is to write something
like dosemu2 and try to get it in. The place
is vacant.

**Comment by jschwartzenberg** [comment] 2019-08-17 20:09
Are there many regressions left? Playing a bit with dosemu1, I see compatibility really increased with dosemu2!

**Comment by stsp** [comment] 2019-08-17 20:20
Most regressions are in comcom32, so I am
fighting through djgpp bugs to cover at least
the most prominent ones.
In any case, at that point I think the regressions
are not as many as the unimplemented features
that are needed for the beta release. For example,
the lack of freedos tools is a regression or an
unimplemented feature? It was in dosemu1 and
we don't have it yet.

**Comment by jschwartzenberg** [comment] 2019-08-17 20:33
Most people just want to run their applications. As long as more of those work, dosemu2 is good to go.

**Comment by stsp** [comment] 2019-10-03 19:52
> @skitt a little off topic, but very important for us, would you consider packaging the djgpp

Just a small announcement:
https://code.launchpad.net/~stsp-0/+recipe/djgpp-daily

Let me say this wasn't easy! A month of slow-poking
at a free time gave nothing, so I spent 2 full days at work
on that and got a warning of a firing possibility, but
completed this nevertheless. :)

This build system is very rusty (does multiple build/install
phases internally, and emulates "make install" by a simple
copy), very heavy (all source archives are in the git tree)
and would be difficult to adapt for different gcc version
(uploading more source archives will make it intolerably large).
But this is all I have and I do not intend to maintain it.
So if @skitt or @jwt27 or anyone else would like to
work on it further - you are very welcome! I'll change the
import URL at launchpad to the new location if someone
takes it up.

**Comment by stsp** [comment] 2019-10-04 11:43
I would also like to point to the thread where I
discussed with gcc developers the possibilities
of implementing the proper cross-compiler build
support:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91879

Since the thread is quite long, here's the brief
summary for the interested parties.
Basically, the only way to build the cross-compiler
(at least the only one currently known to gcc devs...
or at least the only one they decided to share with
me - not sure what statement would be true) is to
simulate the cross-layout with the tricky combination
of sysroot switches:
`--with-sysroot=$prefix/$target --with-build-sysroot=$DESTDIR$prefix/$target
--with-native-system-header-dir=/include`
and a set of symlinks.
That idea was expressed here:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91879#c11
and further explained here:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91879#c13
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91879#c24

Since I wasn't satisfied with such a tricks (in
fact, as you can see from the thread, I had a major
problems to even start understanding all the magic),
the possible extension was suggested by gcc dev:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91879#c22

And a possible extension from me:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91879#c27
(and some posts before that)
Which is what I did (roughly) for my current djgpp
build system.

I would like all the interested parties (@skitt, @tkchia, @djdelorie)
to look into that thread and decide what is to do next.
The current situation where building the cross-compiler
is nearly impossible (or you have to resort to the tricks
suggested by Joseph), is IMHO far from perfection and
something should probably be done about it. But I don't
see any enthusiasm among gcc devs to change that.
Someone should spend a lot of time at analysing the
situation, writing patches and negotiating them with gcc
devs. I didn't do that, I only presented them with a few
hacks I did for my build system, they were not impressed,
and that's it. Much more work is needed to get any further.

**Comment by stsp** [comment] 2019-10-04 17:29
> The biggest challenge to editing the stub is keeping it 2048 bytes or less :-)

Bingo... My patch that just added the "no environment segment" msg
have exceeded that limit. :( Will shorten it to "no envseg" and re-send
the patch.
I was able to fully test my patches only now, as the build system helps.
@djdelorie Is there really no way to make a stub larger than that?
The executables worked fine (which is why I didn't notice any problems
initially), so I suppose the limit is somewhere in binutils?

**Comment by djdelorie** [comment] 2019-10-04 17:38
The stub can be any size you like, but it's been 2k for decades and
there are likely MANY assumptions throughout the code that it's 2k.

Besides, it's much more fun and challenging to squeeze everything into
2048 bytes :-)

I will also note that djgpp-related emails should go to
djgpp@delorie.com (mailing list), not my personal address.

Thanks,
DJ

**Comment by stsp** [comment] 2019-10-04 18:01
> djgpp@delorie.com (mailing list), not my personal address.

Hmm, I don't think I ever sent any e-mail to your personal
address. I don't even know that address. :)
So really not sure why are you saying that.

**Comment by djdelorie** [comment] 2019-10-04 18:04
Ah, nevermind, it's github mailing me as part of its internal
conversation thing.

**Comment by stsp** [comment] 2019-10-05 18:30
@skitt What else is required on my side
to allow the packaging for debian? I think
djgpp was the last obstacle?

Also I wonder if anyone wants to maintain
the packages for fedora. I think @amluto
offered that, but this was long ago.

The specs and debuild recipes are of course
all written already.
