### ISSUE TITLE
Crash in Fedora 25

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#358] opened 2017-04-09 19:22 UTC
I installed Fedora 25 cleanly and tried to install and run dosemu2. It immediately crashes on start-up however.

Attached my boot.log.
[boot.log.txt](https://github.com/stsp/dosemu2/files/908479/boot.log.txt)

**Comment by stsp** [comment] 2017-04-11 13:22
I can't reproduce this, but likely now fixed.

**Closed** 2017-04-11 13:22 UTC

**Comment by jschwartzenberg** [comment] 2017-04-12 12:34
Indeed fixed!

**Comment by stsp** [comment] 2017-04-12 12:50
10x, good to know.
Fewer crashers for next pre.
