### ISSUE TITLE
Mouse not working in terminal mode

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#578] opened 2018-03-10 00:20 UTC
The mouse doesn't work in terminal mode `dosemu -t`. All that happens is the mouse codes output through the keyboard. Per #574 old versions crash so are untestable. Fortunately the mouse works in one terminal.

Outputs mouse codes to keyboard
* XFCETerm (xterm-256color)
* Gnome Terminal (xterm-256color)
* xterm, uxterm (xterm)
* PuTTY (xterm)
* qterminal (xterm)
* pantheon-terminal (xterm-256color)
* Terminator (xterm-256color)
* Tilix (xterm-256color)
* Lilyterm (xterm)

Works
* Termite (xterm-termite)

3/15 edit: Added () `echo $TERM` to each terminal.

**Comment by stsp** [comment] 2018-03-12 13:51
Does anyone else see this?

**Comment by stuaxo** [comment] 2018-03-12 17:10
Was unable to reproduce just now :/  

Only tested in Tilix + Gnome-Terminal, with Free Dos EDIT so far.

**Comment by stsp** [comment] 2018-03-12 17:59
Me neither (gnome-terminal, xterm), and no one else complained in the past.

**Comment by stsp** [comment] 2018-03-13 10:08
Please attach `-D9+km`  log.

**Comment by severach** [comment] 2018-03-14 08:40
[boot.termite.good.log.zip](https://github.com/stsp/dosemu2/files/1810209/boot.termite.good.log.zip)
[boot.xfce.bad.log.zip](https://github.com/stsp/dosemu2/files/1810210/boot.xfce.bad.log.zip)

**Comment by stsp** [comment] 2018-03-14 23:50
Should now be fixed.

**Comment by severach** [comment] 2018-03-15 00:11
Not yet.

[boot.termite2.good.log.zip](https://github.com/stsp/dosemu2/files/1813551/boot.termite2.good.log.zip)
[boot.xfce2.bad.log.zip](https://github.com/stsp/dosemu2/files/1813552/boot.xfce2.bad.log.zip)

**Comment by stsp** [comment] 2018-03-15 01:01
Please re-do the log.

**Comment by severach** [comment] 2018-03-15 04:37
[boot.xfce3.bad.log.zip](https://github.com/stsp/dosemu2/files/1813981/boot.xfce3.bad.log.zip)
[boot.termite3.good.log.zip](https://github.com/stsp/dosemu2/files/1813983/boot.termite3.good.log.zip)

**Comment by stsp** [comment] 2018-03-15 10:59
Please compile this small test program:
https://invisible-island.net/ncurses/tctest.html#download
and post its output for those 2 terminals.

**Comment by severach** [comment] 2018-03-15 18:12
Includes XFCE, xterm, Gnome, and termite.

[tctest.zip](https://github.com/stsp/dosemu2/files/1816594/tctest.zip)

**Comment by stsp** [comment] 2018-03-15 18:22
There is something wrong with your "Km" setting.
On "bad" terminals it is `:Km=\E[<:\` and on good
`:Km=\E[M:\`, as it should be.
Does something change if you do on bad terminals:
`export TERM=xterm-termite`
before running `dosemu -t`?
Also please produce the tctest output after that
command.

**Comment by severach** [comment] 2018-03-15 18:56
Downgrading [ncurses](https://www.archlinux.org/packages/core/x86_64/ncurses/) 6.1 -> 6.0 fixes the problem. Every terminal in the list works.

**Comment by stsp** [comment] 2018-03-15 18:59
So not a dosemu problem.

**Comment by severach** [comment] 2018-03-15 19:44
````
misc/terminfo.src
# As an alternative (and fixing the longstanding limitation of X11 mouse
# protocol regarding button-releases), I provided this:
xterm+sm+1006|xterm SGR-mouse,
  kmous=\E[<, XM=\E[?1006;1000%?%p1%{1}%=%th%el%;,
````

````
sed -e 's:E\[<,:E[M,:g' -i 'misc/terminfo.src'
````

Patching this line fixes it but this line wasn't changed from 6.0 -> 6.1. Something else was changed to put this code into the path of xterm-256color and xterm. xterm-termite was not affected.

Every instance of `\E[<` except this one has more that comes after.

**Comment by stsp** [comment] 2018-03-15 19:57
Please see what `infocmp |grep kmous` says, as
it seems `mc` looks for `kmous` (I have no idea how
and why it differs from `Km` etc).

**Comment by severach** [comment] 2018-03-15 20:08
````
% pacman -Q ncurses # not patched
ncurses 6.1-3

% echo $TERM; infocmp |grep kmous
xterm-termite
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,

% echo $TERM; infocmp |grep kmous
xterm-256color
	kind=\E[1;2B, kmous=\E[<, knp=\E[6~, kpp=\E[5~,
````

````
% pacman -Q ncurses              
ncurses 6.0+20170902-3

% echo $TERM; infocmp |grep kmous                        :(
xterm-256color
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,

% echo $TERM; infocmp |grep kmous
xterm-termite
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
````

**Comment by stsp** [comment] 2018-03-15 20:27
OK, it appears SGR is a new xterm mouse protocol
which dosemu2 does not support and mc does.
Your ncurses altered existing Km/kmous setting
instead of providing the new one, so it broke all
older applications. This is a bug that should be
fixed on their side. Of course my understanding
of the matters may be completely wrong.

**Comment by severach** [comment] 2018-03-15 20:36
It's a bit tricky to capture keyboard and mouse responses. I did it by killing `mc` which leaves mouse mode active then I use `od -c` to dump the codes.

````
^[[<0;28;24M^[[<0;28;24m^[[<2;32;24M^[[<2;32;24m
````

Reporting mouse events through `Esc [ <`- works.

**Comment by stsp** [comment] 2018-03-15 21:28
> Reporting mouse events through Esc [ < works.

Like I said, its a new protocol.
You can change `mouse_xterm.c:105` and replace
last 1003 with 1006 to activate it. But of course
dosemu2 will still not parse it correctly.

> How can a single kmous/Km handle this?

In no way, I suppose.
I think they just broke the compatibility.
Note that previously the new protocol worked
nevertheless in mc as mc had the new value
hardcoded.

**Comment by stsp** [comment] 2018-03-15 21:29
So there was hardly any reason for a breakage.

**Comment by severach** [comment] 2018-03-15 21:41
It's not hardcoded in `mc`. I downgraded to 6.0 and now the `mc` mouse events are `Esc M` instead of `Esc <`. A possible explanation is that `mc` looks at `kmous/Km` to pick the mouse mode. Another possibility is that `ncurses` has gained another hack to make `Km` report the right value so long as you read it after choosing the mouse mode.

**Comment by stsp** [comment] 2018-03-15 21:54
mc hardcodes it:
https://github.com/MidnightCommander/mc/blob/master/lib/tty/tty.c#L313
Then it tries to enable both protocols, and
is prepared to parse both. Maybe the xterm
itself also looks into a termcap database and
doesn't enable the extended protocol under
some conditions? As you said, the "Km" change
is not new, so maybe something else just
prevents the xterm from enabling new protocol.

**Comment by stsp** [comment] 2018-03-15 22:10
This will help you to enable mouse:
`echo -e "\033[?9h\033[?1000h\033[?1002h\033[?1003h"`

You can use 1006 to enable new mode.

**Comment by stsp** [comment] 2018-03-15 22:14
`echo -e "\033[?9h\033[?1000h\033[?1002h\033[?1003h\033[?1006h"`

This enables new mode.
You actually need both 1003 and 1006.
Seems 1006 only affects button presses/releases.

**Comment by stsp** [comment] 2018-03-15 22:19
In fact I think 1003, while using the new escape
code for you, may still use the old protocol if we
don't use 1006. Please check if this is true. If so,
the only change I'll need to do is to hardcode the
new escape. This is feasible.

**Comment by stsp** [comment] 2018-03-15 22:24
Grr, wrong, it doesn't use the new escape
code for you. It only codes it in Km, but
doesn't use. Ignore the prev comment.

**Closed** 2019-02-15 00:44 UTC

**Comment by stsp** [comment] 2019-02-15 00:54
I implemented SGR support, so should now be fixed.
ncurses actually provided the fall-back descriptions,
for example the one could do
`TERM="xterm-1003" dosemu -t`
to get the mouse working, or
`SLtt_initialize("xterm-1003");`
would do the same thing.
And yet I think this was a very hostile compatibility
break.
