### ISSUE TITLE
Fonts aren't always scaled when switching from full-screen to window

### ISSUE THREAD

**Issue by jharrison022** [stsp/dosemu2#437] opened 2017-08-18 00:34 UTC
Using Ctl-Alt-F to switch from full-screen to a window, the fonts aren't always scaled, leaving the window with only the upper-left hand portion of the screen visible.

This happens with -X or -S on the command line.

dosemu-2.0pre7.1-20170817-54-gd7d6e1a
xorg 1.16.4, Intel
Debian 8 (jessie)

**Comment by stsp** [comment] 2017-08-18 13:58
Are you sure this definitely happens with `-X`?
I've seen this only with SDL.

**Comment by jharrison022** [comment] 2017-08-18 22:57
I'm pretty sure it *doesn't* happen with -X.  I was starting dosemu from a shell script that had -S in the command line.

**Comment by stsp** [comment] 2017-08-18 23:29
Duplicate of #350.
Upstream ticket:
https://bugzilla.libsdl.org/show_bug.cgi?id=1859
Please visit this ticket:
https://bugs.launchpad.net/dosemu2/+bug/1679573
and mark it as affecting you, or
fill the same one for debian.

**Closed by stsp** 2017-08-18 23:29 UTC
