### ISSUE TITLE
Direct VGA regression

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#222] opened 2016-08-07 20:29 UTC
It stopped working with this commit:

4354909ed99b89c79783f2a94af8138acc35c4a7 is the first bad commit
commit 4354909ed99b89c79783f2a94af8138acc35c4a7
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Mon Apr 25 22:41:22 2016 +0300

    video: call vga_emu_pre_init() for any video system [#165]

:040000 040000 323f83ca6d78eee7bd9194e4459cd1f252744705 7bc2459cc721167b1d78925fd7e4ab262764f9bd M	src

**Comment by bartoldeman** [comment] 2016-08-07 20:38
Confirmed. Actually I realized that that piece was missing in one of my KVM patches (all other low memory is aliased to shared memory) and then saw that console graphics is broken.

The above commit is not the only issue. There is also an issue with the map to 0xa0000 as it is remapped to the wrong place; however the mode is set correctly and typing exitemu blindly works ok. I am debugging.

**Comment by stsp** [comment] 2016-08-07 23:00
Oh crap, I suspect my kvm_base preparations are
at fault. Thanks guys for taking care of that. :)

**Comment by stsp** [comment] 2016-08-09 17:12
Should now be fixed.
Btw, Bart, adding the word "fixes" before the bug number
makes github to close the related ticket automatically.

**Comment by jschwartzenberg** [comment] 2016-08-13 09:25
Yep, I can confirm it's working again! For some reason Commander Keen 4/5 EGA doesn't work on one system but does work on another (not sure if that's a regression or hardware problem).

Notable is that 'dosemu -s' does not open /dev/kvm here. Does anybody have that combination working?

**Comment by stsp** [comment] 2016-08-13 13:53
> Notable is that 'dosemu -s' does not open /dev/kvm here.

On 32bit systems it is not default yet.
Maybe it should be once the VGA speed-ups are
worked out properly, because kvm can beat vm86
in vga emulation speed.

**Comment by bartoldeman** [comment] 2016-08-13 14:02
If you set $_cpu_vm="kvm" direct console graphics work with KVM. The only issue is that all VGA port accesses are trapped (with "vm86" most of the I/O goes direct, which may slow down some games (in particular those that use 16-color planar VGA modes). I haven't tested it much though. Perhaps with IOMMU it could be faster.

**Comment by stsp** [comment] 2016-08-13 14:11
> If you set $_cpu_vm="kvm" direct console graphics work with KVM.
> The only issue is that all VGA port accesses are trapped

Oh! This is likely related to your comment
"c. I/O bitmap, for now set to trap all ints. Todo: sync with ioperm()"
so hopefully is not forever.

> Perhaps with IOMMU it could be faster.

Isn't IOMMU mainly for DMA?
I think it can be faster if we just handle ioperm(), or
is this not the only problem here?

**Comment by bartoldeman** [comment] 2016-08-13 15:36
KVM has its own i/o bitmaps inside the kernel and there is no api to change them.

If I fiddle the i/o bitmap in the guest TSS i/o instructions with cause a VMEXIT instead of a guest GPF. I timed both approaches and there is little difference (about 2 microseconds per i/o ins).

**Comment by stsp** [comment] 2016-08-13 16:05
> KVM has its own i/o bitmaps inside the kernel and there is no api to change them.

You mean the ones besides those accessible with ioperm()?
Oh. :(

**Comment by jschwartzenberg** [comment] 2016-08-13 16:54
I put $_cpu_vm = "kvm" in /etc/dosemu/dosemu.conf as well now, but still dosemu does not use /dev/kvm when I run it with -s. When I run it without -s, kvm is used.

**Comment by stsp** [comment] 2016-09-08 10:40
I changed the Bart's mapping fix a bit.
It was very good for the release, but now the more
extensive fix can be added.
Would be nice to get the confirmation that the thing
still works, and the ack/nack from Bart. :)

**Comment by bartoldeman** [comment] 2016-09-09 13:08
Nack :)

you need a patch like this:
--- a/src/arch/linux/mapping/mapping.c
+++ b/src/arch/linux/mapping/mapping.c
@@ -544,7 +544,7 @@ static int do_map_hwram(struct hardware_ram *hw)
     error("mmap error in map_hardware_ram %s\n", strerror (errno));
     return -1;
   }
-  hw->vbase = DOSADDR_REL(p);
+  hw->vbase = hw->default_vbase = DOSADDR_REL(p);
   g_printf("mapped hardware ram at 0x%08zx .. 0x%08zx at %#x\n",
             hw->base, hw->base+hw->size-1, hw->vbase);
   return 0;

otherwise default_vbase is always set to -1 for the LFB and everytime it is mapped in mmap will try to find a new memory area which fails very quickly.

**Comment by stsp** [comment] 2016-09-09 20:37
> otherwise default_vbase is always set to -1 for the LFB

But that's the whole point!
Please see the above new patch (in the separate branch) -
is this OK?

**Comment by stsp** [comment] 2016-09-09 20:41
> But that's the whole point!

Hmm, but it is probably not OK to change the
vbase at random points, esp if the app have already
taken the pointer to lfb...
So I guess this is still wrong.

**Comment by stsp** [comment] 2016-09-09 23:28
I added more patches to the map_tweaks, hope
now its fine. Bart, could you please review?

**Comment by stsp** [comment] 2016-09-11 21:40
OK, no review - merged. :)
Could someone please test?
Ack/nack would be great too.

**Comment by stsp** [comment] 2016-09-16 20:17
OK, so no one tests.

**Comment by jschwartzenberg** [comment] 2016-09-16 20:36
I'll test of course!! Just didn't have much time these days.

**Comment by bartoldeman** [comment] 2016-09-16 21:23
Same for me. It is broken for me. I am working on fixing it but it is a tough one to fix (unless I simply comment out pin_hardware_ram() and unpin_hardware_ram(), then I can run and exit dosemu without switching VCs).

**Comment by stsp** [comment] 2016-09-16 21:35
Damn. :)

**Comment by bartoldeman** [comment] 2016-09-16 22:07
I think I am quite close to fixing it this weekend...

**Comment by bartoldeman** [comment] 2016-09-18 18:17
It is the COPYBACK on LFBs that hangs dosemu. This was disabled (to VGA hardware memory) with a comment in mapping.c saying "XXX" before your most recent changes. The copy from VGA hardware memory is also problematic -- I need to study the source a bit more to see how that was handled.

**Comment by stsp** [comment] 2016-09-18 21:36
Thanks Bart!
I think XXX applied to cpy _from_ H/W memory actually.
Should I comment the copyback in the unpin_hardware_ram()?
I wonder if it applies to just your video card or some bug
in the code...

**Comment by stsp** [comment] 2016-09-18 22:31
store_vga_mem() already seems to be doing this,
but via the lowmem-mapped pages. It doesn't copy
from LFB directly! I remember I was involved with
writing that code, but I completely forgot why do we
use low page mappings instead of directly accessing
lfb. There was probably the good reason to, in which
case copyback directly from lfb doesn't work? No idea.

**Comment by bartoldeman** [comment] 2016-09-19 13:07
After looking at the code a bit more:
* copyback was only used (except the init case below) for !config.vga, i.e. the somewhat obscure Video=&Video_console (not Video_graphics) settings. This setting only works if the Linux console uses plain vga text mode, directly maps video ram, but not i/o ports, and support text mode page flipping emulation using mmap. I cannot even figure out anymore how to boot my newest laptop using vgacon (with "nomodeset" from grub from EFI bios the console uses simplefb). So to test that ($_console=(1), $_graphics=(0)) I would need to run dosemu in linux in qemu or bochs etc to simulate older hardware.

* when dosemu starts vga_post_init() calls set_vc_screen_page() which calls get_video_ram(WAIT) with scr_state.mapped==1, which in turn calls unmap_video_ram(1) with unconditional copyback (and calls map_video_ram in the same function a little later so this all looks a bit pointless unless a text mode page is flipped for Video_console). In dosemu1, unmap_video_ram then called alias_mapping on lowmem only; in dosemu2, commit 41fd0b10 this was changed to unmap_hardware_ram('v',cap) with the //XXX comment for LFB copyback.

* store_vga_mem() uses LFB via vesa_get_lfb(). It doesn't try to save and restore all the PCI mem regions that are mapped, only whatever the VESA BIOS reports as the base and amount.
What did not work for you at the time is the special "all memory access mode" (see vbe.c).

Two choices:
1. Only do copyback for Video_console() (fairly easy to do, just check for !config.vga)
or
2. Junk Video_console (a bigger patch).

**Comment by stsp** [comment] 2016-09-19 21:46
> copyback was only used (except the init case below) for !config.vga, i.e.
> the somewhat obscure Video=&Video_console (not Video_graphics) settings.

So why not to do copyback also for config.vga?
Yes, dosemu freezes when switched away, but
IIRC you can unfreeze it with dosdebug, and in
any case, why video_console is that different?

> So to test that ($_console=(1), $_graphics=(0)) I would need to run dosemu in linux
> in qemu or bochs etc to simulate older hardware.

I suppose we really don't need this any more.
If it was ever used in the past, we now have a good
term plugin.

> with scr_state.mapped==1, which in turn calls unmap_video_ram(1) with unconditional
> copyback (and calls map_video_ram in the same function a little later so this all looks a
> bit pointless unless a text mode page is flipped for Video_console).

I wonder if it is broken for long.
map_video_ram() seems to be going to set the video page to
map, but our hwram API simply doesn't take the phys page addr
as an argument. So I think this page flipping thingy was broken
long before my patch.

> 1. Only do copyback for Video_console() (fairly easy to do, just check for !config.vga)

I am not sure I understand why video_console is special.
You seem to be implying that dosemu1's way of doing things
was right, but that still doesn't explain what do we have broken
now. Why copyback doesn't work with config.vga?

> 2. Junk Video_console (a bigger patch).

You mean remove?
I support that option, but I wonder how will it fix the config.vga case.
How about just disabling the copyback on the LFB? At least as
long as:
1. we seemingly don't know what breaks
2. having no copyback on LFB was proven to work right

**Comment by stsp** [comment] 2016-09-20 10:36
I would expect that video_console is special
in a way that it doesn't freeze when switched
away, works in background. That would explain
the need of the copyback. But I don't see the
check that avoids the freeze when console_video && !vga,
so I suppose it also freezes when switched.
Of course we could fix it to not freeze and then
see what to do with config.vga if it gets unfreezed
with dosdebug... but likely its much simpler to
remove video_console and avoid copyback for
kmem entirely (and then I wonder if we ever need
copyback at all).

**Comment by bartoldeman** [comment] 2016-09-20 12:22
I think commit 41fd0b1 broke most of the page flipping for !config.vga. I tried to keep it working back in the day in dosemu1 because it was there and I wanted to stay backwards compatible but I may have been the only user of it.

> but likely its much simpler to remove video_console and avoid copyback for kmem entirely (and then I wonder if we ever need copyback at all).

yes exactly. From my personal point as a user/developer I like console graphics because it shows what should be shown in case of issues with vgaemu, without needing to mess around with a native DOS partition.

The simplest way to have that is to just have save/restore and freeze. In that case the kmem mappings can even be permanently fixed, no need to mremap them ever.

We just have this long dosemu history (in the very early years, think 1995) of various attempts to have some kind of limited vgaemu while dosemu was switched away in the background. Then we concluded that this was pretty much impossible given the limitations of ioperm once root privs are dropped (if you drop an ioperm you lose it forever) and froze (I guess the !config.vga case was forgotten here since it is so little used). But the old now untested code remained for a long time.

BTW the copyback on LFB really tried to copy all PCI regions instead of $_vmemsize at the BIOS-reported LFB. This is quite a lot on modern cards (I have two regions, one of 256MB and another of 16MB, 272MB total); and takes around 5 seconds in the direction it works for me (hardware->system RAM).

**Comment by stsp** [comment] 2016-09-20 13:00
> The simplest way to have that is to just have save/restore and freeze. In that
> case the kmem mappings can even be permanently fixed, no need to mremap them ever.

Exactly.
So would you mind preparing the patch that
simply removes the calls to pin/unpin_hardware_ram(),
and, if it works, submit a PR? The larger patch of removing
the video_console (!vga case) would be welcome too, but I
can do that myself if you don't have time. Hope I won't break
too much when removing, so perhaps it will work without
testing (wishful thoughts :)

> BTW the copyback on LFB really tried to copy all PCI regions instead of $_vmemsize

That's the nature of copyback, but I think this was a mistake
to implement such interface (yes, I know it was me, but 10 years
ago it looked like it can be useful). Today, if we need something
like this, I'd let vga or vesa subsystems to do the copyback stuff
with the ways they know about: vga would copy only the lowmem
part and vesa could copy $_vmemsize. But since this would be
needed only for dosdebug that can unfreeze dosemu, I'd rather
just remove copyback entirely after removing video_console.

**Comment by stsp** [comment] 2016-09-21 08:50
> I think commit 41fd0b1 broke most of the page flipping for !config.vga.

Maybe, but it was broken in linux kernel too,
since about 2011, and fixed only here:
https://patchwork.kernel.org/patch/7955451/
https://patchwork.kernel.org/patch/7955461/
This was one of the results of the (quite large)
"please stop breaking dosemu" campaign, during
which Linus asked some kernel devs to fix all
dosemu-related regressions (he stripped public
MLs from CC, so this is not publicly available).

**Closed** 2016-10-15 23:40 UTC

**Comment by stsp** [comment] 2016-10-15 23:42
I removed the kmem flipping code completely.
Hope the console switching will no longer break
from every breathe. :)
Someone should remove all !config.vga code too.
