### ISSUE TITLE
Sid & Al's Incredible Toons (The Incredible Toon Machine for DOS) has resolution and mouse issue

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#218] opened 2016-07-27 19:54 UTC
Sid & Al's Incredible Toons has an extra bar at the top which displays graphics from the bottom. Also the mouse can't reach the right part of the screen.

More info about the game: http://www.abandonia.com/en/games/30820/Sid+%2526+Als+Incredible+Toons.html

**Comment by jschwartzenberg** [comment] 2016-07-27 20:21
This one is improved over 1.4. Only a very small area is reachable in that version. The graphics issue is also there.

Another note: both 2 and 1.4 seems to have issues with sound effects when clicking for instance the button remote to open/close the right sidebar.

**Comment by jschwartzenberg** [comment] 2016-08-08 19:43
The graphics issue is fixed in a newer version of the game (1993 release VS 1992 one) the mouse issue is not.

**Comment by jschwartzenberg** [comment] 2016-08-08 19:54
The Incredible Machine 2 has the same mouse and sound issues.

**Comment by stsp** [comment] 2016-08-14 18:54
Please see with the native driver if it
doesn't do the cursor slowdown. Yes, the
slowdown is now ignored, but it could still
downscale the coords by hands.

If there is a gfx issue, should be reported
separately.

**Comment by jschwartzenberg** [comment] 2017-02-13 21:05
Seems I missed your request here. What do you mean exactly with native driver here? I think I remember we chatted about the graphics issue as this was probably just a game bug.

I can confirm that the sound sticking issue is indeed fixed as you mentioned in #219.

**Comment by jschwartzenberg** [comment] 2017-02-13 21:07
One sound effect is still doubled though. The one of the clapper. I don't think it's supposed to be like that.

**Comment by jschwartzenberg** [comment] 2017-02-13 21:09
TIM2 also still has some repeating sounds and the same mouse issue as Toons.

**Comment by stsp** [comment] 2017-02-14 01:51
Some more repeating sounds should now be fixed.
But probably not all of them still...

**Comment by stsp** [comment] 2017-02-24 13:13
I think all sound problems are now fixed.
Mouse problem is interesting: I can't reproduce
it when mouse debugging is enabled. :(

**Comment by stsp** [comment] 2017-02-24 16:15
I managed to reproduce with debug, but
I think its a game's bug. I tried with native
drivers, all have the same problem. Plus,
with gmouse and lmouse it has a lot of
video problems (wrong colors, square around
mouse pointer etc) and no gfx artifacts
only with mouse.com from MS.
So I think this and other similar tickets should
be closed. If you agree, please close.

**Comment by stsp** [comment] 2017-02-24 16:21
The problem I am talking about is that the
program ignores the mouse clicks in the screen
where puzzle should be selected (mouse
works in other screens though).

**Comment by jschwartzenberg** [comment] 2017-02-25 16:36
It indeed seems there are mouse issues in general with these games. I searched a bit around:
http://www.sierrahelp.com/XPHelp/MouseProblems.html

It seems there's also a strange IRQ issue:
https://sourceforge.net/p/dosbox/bugs/156/
It's mentioned here as well: http://www.sierrahelp.com/Utilities/SoundUtilities/GOSiERRA.html

If these games can't really be supported, I would suggest something in the readme about it. I can imagine that more Sierra games would be affected, but most will work in ScummVM. The Incredible Machine also has a Windows version which should run better in dosemu as well. (Wine gave problems last time I tried it.)
I should test some Sierra adventure games I guess.

**Comment by stsp** [comment] 2017-02-25 17:59
> If these games can't really be supported, I would suggest something in the readme about it.

Would you mind making a PR then, please? :)
I think it should go to emufailures.txt

None of the URLs you've found, seem to mention
our problem. But you can try native mouse drivers
just to see that yourself.

**Comment by stsp** [comment] 2017-02-25 18:03
Should this be closed?

**Comment by jschwartzenberg** [comment] 2017-02-25 21:29
This is on the page behind the first URL
```
Mouse Confinement

Your mouse cursor may be confined to the upper or upper left-hand side of screen. Some games or applications that require high-resoultion VESA video modes will experience problems with the mouse cursor under Windows NT4, Windows 2000 and Windows XP. This is caused by the fact that Windows' mouse emulation (int 33h, functions 3, 5 and 6) will only recognize horizontal coordinates between 0 and 639, and vertical coordinates between 0 and 199.
```

Isn't that the same we see in dosemu?

**Comment by stsp** [comment] 2017-02-26 08:05
Have never seen that.
With mouse grab it works perfectly.

**Comment by jschwartzenberg** [comment] 2017-02-26 17:00
Yep, with mouse grab the whole screen is reachable. I guess there's no proper way to let it work without mouse grab then.

**Comment by stsp** [comment] 2017-02-26 17:02
Indeed.

**Closed by stsp** 2017-02-26 17:02 UTC
