### ISSUE TITLE
install still checks kernel.sys

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#666] opened 2018-08-18 23:19 UTC
install.c refuses to install dosemu's home
dir if there is no freedos. This prevents fdpp
from taking over the control.
It may be too early to remove this check
now though, as w/o freedos there is no
command.com. Once comcom32 is properly
integrated, install.c should be updated to
stop checking for freedos.

**Comment by stsp** [comment] 2018-09-22 11:27
The files you mentioned, are long ago gone.
Even with freedos available, the boot
happens directly from the system-wide dir.
We can't create the skeleton, or at least
not all that simple. Skeleton consists not
only of drive C, but also of the links to
freedos/fdpp dirs. If we don't create them
at all, then we won't be able to do that
later. Of course we can disable them at
runtime, but note that just installing
freedos later, will not get them enabled,
because the freedos path is iirc hardcoded
during build. So "disabled" dosemu will
never find freedos (I may need to re-check
if this is still true). Also the one needs to
make sure the disclaimer is ptesented
only if there is something to boot.
So if you can address these problems,
then fine. But the outcome will be very
small, as no one except you wants to
install some other dos manually.
We can solve this problem properly if
we can invest some time into it.
comcom32 will be there as soon as we
get a ppa for djgpp. As you know, this
stuck for a moment. We should in a mean
time concentrste on an installation
scripts that Julius wrote. Then we will
be able to install any dos. Its just a matter
of reviewing them and glewing to install.c.
So please choose any solution you like.
If you can properly do skeleton creation,
please go for that.

**Comment by stsp** [comment] 2018-09-22 12:02
Um, we already have `dosemu --install`.

**Comment by andrewbird** [comment] 2018-09-22 12:15
I guess my unfamiliarity is due to never running dosemu outside of the development directory. I couldn't find `dosemu --install` but its help printed hinted at `dosemu -i`. That created
~~~
ajb@polly:~$ rm -rf ~/.dosemu
ajb@polly:~$ dosemu -i
ERROR: fdpp support not compiled in or not found:
ERROR: libfdpp.so: cannot open shared object file: No such file or directory
ERROR: Using CPU emulation because vm.mmap_min_addr > 0
You can most likely avoid this problem by running
sysctl -w vm.mmap_min_addr=0
as root, or by changing the vm.mmap_min_addr setting in
/etc/sysctl.conf or a file in /etc/sysctl.d/ to 0.
If this doesn't help, disable selinux in /etc/selinux/config
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: vde_switch failed: sh: 1: vde_switch: not found
ERROR: Bootable drive not found, exiting
ajb@polly:~$find .dosemu -ls
  3506181      4 drwxr-xr-x   4 ajb      sphere       4096 Sep 22 13:06 .dosemu
  3422624      4 -rw-r--r--   1 ajb      sphere       4069 Sep 22 13:06 .dosemu/boot.log
  3433935      4 -rw-r--r--   1 ajb      sphere        253 Sep 22 13:06 .dosemu/disclaimer
  3506182      4 drwx------   2 ajb      sphere       4096 Sep 22 13:06 .dosemu/run
  3506190      4 drwxr-xr-x   2 ajb      sphere       4096 Sep 22 13:06 .dosemu/drives
  3433941      4 -rw-r--r--   1 ajb      sphere         13 Sep 22 13:06 .dosemu/drives/d.lnk
  3433961      4 -rw-r--r--   1 ajb      sphere         14 Sep 22 13:06 .dosemu/drives/f.lnk
  3433937      0 lrwxrwxrwx   1 ajb      sphere         25 Sep 22 13:06 .dosemu/drives/c -> /usr/share/dosemu/freedos
  3433943      4 -rw-r--r--   1 ajb      sphere         22 Sep 22 13:06 .dosemu/drives/e.lnk
ajb@polly:~$ for i in .dosemu/drives/[def].lnk ; do cat $i && echo ; done
${FDBOOT_DIR}
${DOSEMU_COMMANDS_DIR}
${FREEDOS_DIR}
~~~

Thanks

**Comment by stsp** [comment] 2018-09-22 12:32
So is this what you want?

**Comment by andrewbird** [comment] 2018-09-22 12:38
Not really, but I don't want to disappear down a rabbit hole. I'll just make it by hand each time I trash the installation.

Thanks again.

**Comment by stsp** [comment] 2018-09-22 13:07
But you asked for a skeleton and it does.
What remained?

**Comment by andrewbird** [comment] 2018-09-22 14:05
The following gives me what I need, but like you said it's only me that wants to install some other DOS manually.
~~~
mkdir -p .dosemu/drives/c
cp autoexec.bat config.sys .dosemu/drives/c/.
(cd .dosemu/drives/c/. && ln -s /usr/share/dosemu/dosemu2-cmds-0.1/dosemu .)
~~~

**Comment by stsp** [comment] 2018-09-22 14:33
Then its a bug, C seems to be wrongly
created. Please fill it and/or fix. :)

**Comment by stsp** [comment] 2018-09-22 15:30
Yes. It symlinked C somewhere for the
reasons that are hardly valid.

**Comment by stsp** [comment] 2018-09-22 21:15
I made it to create default layout and run fdpp.
Is this what you need?

**Comment by andrewbird** [comment] 2018-09-23 11:08
Yes it seems to do what I need for drive `C:`, although I didn't try fdpp. I was slightly confused by the second question's wording, the option that worked for me was `or press [ENTER] to quit if you suspect an error after manual installation.`

~~~
Welcome to DOSEMU2
This program is  distributed  in  the  hope that it will be useful,
but  WITHOUT  ANY  WARRANTY;   without even the implied warranty of
MERCHANTABILITY  or  FITNESS FOR A PARTICULAR PURPOSE. See the files
COPYING for more details.
Press ENTER to confirm, and boot DOSEMU2, or [Ctrl-C] to abort
 
 
DOSEMU-FreeDOS is not available to boot DOSEMU.
Please enter the name of a Linux directory which contains a bootable DOS, or
press [Ctrl-C] to abort for manual installation of FreeDOS or another DOS, or
press [ENTER] to quit if you suspect an error after manual installation.
~~~

The assignment of .lnk files to drive contents doesn't seem to be as intended, but I presume that's because the FreeDOS boot drive is missing and so the commands are then off by one.
~~~
ajb@polly:~/.dosemu$ for i in drives/?.lnk; do cat $i ; echo " # $i" ; done
${FDBOOT_DIR} # drives/d.lnk
${DOSEMU_COMMANDS_DIR} # drives/e.lnk
${FREEDOS_DIR} # drives/f.lnk
~~~

~~~
 C:\>dir d:
 
 Volume in drive D is u2-cmds-0.1
 Directory of D:\
 
AUTOEMU  BAT       561 09-23-18   4:02a
DOSEMU       <DIR>     09-23-18  11:37a
AUTOEXEC BAT       642 09-23-18   4:02a
FDCONFIG SYS       263 09-23-18   4:02a
CONFIG   SYS       529 09-23-18   4:02a
        5 file(s)       1995 bytes
                  2147450880 bytes free
 
C:\>dir e:
Invalid drive specification
 
C:\>dir f:
Invalid drive specification
~~~

So fine for my purpose, some manual fiddling is expected. Thanks.

**Comment by stsp** [comment] 2018-09-23 11:30
I also don't understand what does this
mean, and most of the code in install.c
looks nonsensical. So I took a strategy
of just rewriting it the way I need, w/o
looking at what was intended. The results
are sometimes like this: confusing messages.
Feel free to open bugs and PRs.

As for not having D:, that's quite bad!
Since you have neither freedos nor fdpp,
you get D missing. Now its normally an
unbootable setup, unless you install DOS
to C by hands, which is what you did. And
I think we need to support that properly,
but I don't see any other solution than to
swap D and E. And I wonder if people will
hate me for always doing the incompatible
changes... I had to create a more flexible
symlink system. I can use the opaque variables
like `D_DEFAULT`, `E_DEFAULT` etc. In that
case I will be able to change the layout any
time I want. Will do.

**Comment by andrewbird** [comment] 2018-09-23 11:39
Any reason during `dosemu -i` when making the drive_c you can't add a filesystem symlink to `${DOSEMU_COMMANDS_DIR}` as then you don't need the separate drive for it? This works quite nicely for me.
~~~
ajb@polly:~/.dosemu/drive_c$ ln -s /usr/share/dosemu/dosemu2-cmds-0.1/dosemu
~~~

I wonder if something similar could be done in the normal FreeDOS based install, but as I don't have it installed I don't actually know what the contents of the {FDBOOT_DIR} should look like.

**Comment by stsp** [comment] 2018-09-23 13:31
Filesystem symlinks do not work because
commands embed the dosemu version.
If I do some incompatible changes, I'll be
able to name them dosemu2-cmds-0.2 etc.
When someone bisects or downgrades,
the appropriate commands will be used,
depending on the running dosemu. This
is the whole point of such symlinks.
And what you say doesn't work anyway
because autoexec.bat sets commands
path to E. I think I should start versioning
also the boot dir so that I can change
config/autoexec only for particular dosemu
version, retaining the compatibility.
Quite a lot of work...

**Comment by andrewbird** [comment] 2018-09-23 14:28
I'm not sure why you need the version number in `{DOSEMU_COMMANDS_DIR}` it will always be resolved to the location that matches the dosemu current binary, but I understand that at the moment it does and hence the symlink value is fixed on `dosemu -i`. Short of autoexec.bat knowing the letter of the boot drive I don't see a way to set the path correctly to avoid hardcoding `E:\dosemu` even if the version was removed from `{DOSEMU_COMMANDS_DIR}`. Oh well, not to worry :smile:

**Comment by stsp** [comment] 2018-09-23 14:42
> I'm not sure why you need the version number in {DOSEMU_COMMANDS_DIR} it will always
> be resolved to the location that matches the dosemu current binary

Because you need multiple set of commands
being installed in parallel.

> even if the version was removed from {DOSEMU_COMMANDS_DIR}.

Not sure what removing will gain, but
adding version to boot dir will allow to
have multiple autoexecs in parallel, with
dosemu finding the needed one by its
version.

**Comment by andrewbird** [comment] 2018-09-23 14:59
> Because you need multiple set of commands
being installed in parallel.

I'm not sure about the usefulness of this:
- do you see the DOS command interface changing between versions? The example I can think of here is `lredir` and `lredir2`, both are currently maintained by you, but the user selects which one to use not based on its unix filesystem location, but on it's DOS name.
- if it's the interface between dosemu and the DOS command, surely the version that a user has to run is the version that shipped with the dosemu.bin. Unless you have two versions of dosemu2 installed, what's the point of the different directories?

**Comment by stsp** [comment] 2018-09-23 15:35
At times you can have multiple dosemu
versions. For example when bisecting. And
no, not only you and me can bisect. Many
our friends here do bisecting too. And when
bisecting, you don't do make install every
time: you start dosemu from the build dir.
I guess the start from the build dir can be
detected to take commands from the build
dir as well. This will solve the part of the
problem. Another part is that while newer
make install should clean all the previous,
the older make install will not clean things
from newer dosemus, so when installing
older versions, you can end up with some
mix of things. Since in the early days of
dosemu2 the commands were changed
very frequently, I figured versioning might
be the good idea, especially when many
people wanted to run dosemu1 in parallel.
Today it is less relevant of course, but the
bisect problem must be solved if we are
to remove versioning.
Someone really should start opening tickets,
or all these discussions will get forgotten.

**Comment by stsp** [comment] 2018-09-23 15:40
Note that independently of versioning,
symlinks via variables are still needed.

**Comment by jschwartzenberg** [comment] 2018-09-23 18:55
> but I don't see any other solution than to
> swap D and E. And I wonder if people will
> hate me for always doing the incompatible
> changes...

People should not rely on fixed drive letters but use things like PATH instead to get to executables.

**Comment by stsp** [comment] 2018-09-23 19:17
The problem is not in people.
The problem is the default layout
created by install.c. If it frequently
stops working, people are annoyed.
Thats why I need to add more and
more indirections to be able to change
things while not changing the default
layout.

**Comment by stsp** [comment] 2018-09-27 21:08
> if it's the interface between dosemu and the DOS command, surely the version
> that a user has to run is the version that shipped with the dosemu.bin.

It appears not that simple.
If I change the default layout, which is what
I now did for #676, then things may stop working
for people who upgrade dosemu2 and do not upgrade
the home-dir installation. Which is pretty much all
users. So I add version to install new commands to
the separate dir, and I also change the variable name
that accesses it. This is what I temporarily forgot in this
thread, but recalled now when fixing #676. So newer
installations will find new commands, and old installations
(newest dosemu2 binary but old layout at home dir)
will find old commands.
Unfortunately I think this trick only works for `make install`
but not for those who use package managers, as
package managers will remove the previous command
dir, whereas `make install` leaves it alone.
Since in the past the package managers were not
integrated in our build process, there were no such
problem, so I invented this versioning. Now I used it
(for the first time actually), and lets see how many
people will complain... I never suggested building
dosemu2 to the package and installing from that -
users should use `make install`. And I hope not too
many people get dosemu2 from launchpad, as freedos
is not provided there. :) So I hope actually not too
many people will suffer, but lets see.

Could you please confirm the layout now is what you
asked for?

**Comment by stsp** [comment] 2018-09-28 00:01
Also note that filesystem symlinks are
very bad for example when prefix changes
(dosemu gets installed locally and later
via package manager). Also they create
the read-only files on C. The idea is to
give C to the user exclusively, having
only other drives read-only.

**Comment by andrewbird** [comment] 2018-09-28 08:53
So yes with removed `.dosemu` and `dosemu -i` I get
~~~
ajb@polly:~$ find .dosemu -ls
  3489804      4 drwxr-xr-x   5 ajb      sphere       4096 Sep 28 09:38 .dosemu
  3434835      4 -rw-r--r--   1 ajb      sphere       4069 Sep 28 09:38 .dosemu/boot.log
  3443882      4 -rw-r--r--   1 ajb      sphere        253 Sep 28 09:38 .dosemu/disclaimer
  3489848      4 drwx------   2 ajb      sphere       4096 Sep 28 09:38 .dosemu/run
  3489896      4 drwxr-xr-x   2 ajb      sphere       4096 Sep 28 09:38 .dosemu/drives
  3444214      4 -rw-r--r--   1 ajb      sphere         18 Sep 28 09:38 .dosemu/drives/d.lnk
  3477095      4 -rw-r--r--   1 ajb      sphere         18 Sep 28 09:38 .dosemu/drives/f.lnk
  3444189      0 lrwxrwxrwx   1 ajb      sphere         25 Sep 28 09:38 .dosemu/drives/c -> /home/ajb/.dosemu/drive_c
  3476981      4 -rw-r--r--   1 ajb      sphere         18 Sep 28 09:38 .dosemu/drives/e.lnk
  3489864      4 drwxr-xr-x   3 ajb      sphere       4096 Sep 28 09:38 .dosemu/drive_c
  3489890      4 drwxr-xr-x   2 ajb      sphere       4096 Sep 28 09:38 .dosemu/drive_c/tmp
~~~

Copying in io.sys, msdos.sys and command.com from MS-DOS 5.00 gives me a bootable drive. Of course there's no `autoexec.bat` or `config.sys` there so the path is not set nor are the usual drivers loaded. 
`c:\dosemu\lredir` shows me that `C:` and `D:` are redirected as expected.

> Also note that filesystem symlinks are
very bad for example when prefix changes
(dosemu gets installed locally and later
via package manager).

In my ideal world `${BOOT_DRIVE}:\dosemu` would be a symlink created at each boot to point to the commands directory, but no matter.

Thanks again, there's probably nothing more to do for me here.

**Comment by stsp** [comment] 2018-09-28 10:14
You can think of it exactly as a symlink
recreated at each boot, using the env var
as a path value. Note that if you put such
symlink on C, you will likely end up putting
the same symlinks for fdconfig/autoexec,
creating the read-only files on C. With
fdpp we can avoid this.

**Closed** 2018-10-30 16:16 UTC
