### ISSUE TITLE
PC/GEOS freezes with VM86, KVM ok

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#209] opened 2016-07-13 22:36 UTC
I'm unable to run PC/GEOS with DOSEmu2 and `vm86` mode without a freeze after 1 or 2 seconds. FreeDOS alone works, but as soon as I start PC/GEOS and it switches to graphics mode, it freezes and CPU usage of DOSEmu2 stays over 100%. With `kvm` everything works flawless. Also DOSEmu 1.4.0.1 and `vm86` is working fine on this 32-bit Ubuntu 16.04 notebook. 

I've tried different commits, but I'm unable to find any working ones I've used before. But I'm sure that I had it running with DOSEmu2 too on this notebook. I get the impression, that something other of the underlying system has changed...

Currently, when running with full debug (-D+a), I get a `boot.log` of 62MB. A little bit to much for posting. A quick check in the log reveal a lot of `vga_emu_fault` entries:
```
VBE: [0x05.0] vbe_display_window::set: return value 0
HLT: fcn 0x0114 called in HLT block, handler: ints thread non-revect +0x10
HLT: fcn 0x0103 called in HLT block, handler: int return +0
VGAEmu: vga_emu_fault: write access to bank region, address 0xa0000, page 0xa0, vga page 0x0
VGAEmu: vga_emu_fault: in_dpmi 0, err 0x6, scp->cs:eip 0073:b77b0c31, vm86s->cs:eip 441a:14fa
VGAEmu: vga_emu_fault: cs:eip = 441a:14fa, instr: f3 ab 2b fa 2b fa 4d 74 14 03 fe 72 08 2e 39 3e
VGAEmu: vga_emu_protect_page: 0xa0 = RW
MAPPING: mprotect, cap= VGAEMU, addr=0xa0000, size=1000, protect=7
VGAEmu: vga_emu_protect: error = 0, region = 0, page = 0x0 --> map_addr = 0xa0, prot = RW
VGAEmu: vga_emu_protect_page: 0xb3433 = RW
VGAEmu: vga_emu_protect: error = 0, region = 1, page = 0x0 --> map_addr = 0xb3433, prot = RW
vgaemu: set page 0 dirty
Return for SIGNAL
VGAEmu: vga_emu_fault: write access to bank region, address 0xa1000, page 0xa1, vga page 0x1
VGAEmu: vga_emu_fault: in_dpmi 0, err 0x6, scp->cs:eip 0073:b77b0c31, vm86s->cs:eip 441a:14fa
VGAEmu: vga_emu_fault: cs:eip = 441a:14fa, instr: f3 ab 2b fa 2b fa 4d 74 14 03 fe 72 08 2e 39 3e
VGAEmu: vga_emu_protect_page: 0xa1 = RW
MAPPING: mprotect, cap= VGAEMU, addr=0xa1000, size=1000, protect=7
VGAEmu: vga_emu_protect: error = 0, region = 0, page = 0x1 --> map_addr = 0xa1, prot = RW
VGAEmu: vga_emu_protect_page: 0xb3434 = RW
VGAEmu: vga_emu_protect: error = 0, region = 1, page = 0x1 --> map_addr = 0xb3434, prot = RW
vgaemu: set page 1 dirty
Return for SIGNAL
VGAEmu: vga_emu_fault: write access to bank region, address 0xa2000, page 0xa2, vga page 0x2
VGAEmu: vga_emu_fault: in_dpmi 0, err 0x6, scp->cs:eip 0073:b77b0c31, vm86s->cs:eip 441a:14fa
VGAEmu: vga_emu_fault: cs:eip = 441a:14fa, instr: f3 ab 2b fa 2b fa 4d 74 14 03 fe 72 08 2e 39 3e
VGAEmu: vga_emu_protect_page: 0xa2 = RW
MAPPING: mprotect, cap= VGAEMU, addr=0xa2000, size=1000, protect=7
VGAEmu: vga_emu_protect: error = 0, region = 0, page = 0x2 --> map_addr = 0xa2, prot = RW
VGAEmu: vga_emu_protect_page: 0xb3435 = RW
VGAEmu: vga_emu_protect: error = 0, region = 1, page = 0x2 --> map_addr = 0xb3435, prot = RW
vgaemu: set page 2 dirty
Return for SIGNAL
```
At the end before `leave_dos` I have only hundreds of this:
```
HLT: fcn 0x022c called in HLT block, handler: ints thread revect +0x28
HLT: fcn 0x0233 called in HLT block, handler: ints thread revect +0x2f
INT2F at fc00:0233: AX=1680, BX=0d0f, CX=0004, DX=0003, DS=02a1, ES=02a1
HLT: fcn 0x0233 called in HLT block, handler: ints thread revect +0x2f
HLT: fcn 0x022c called in HLT block, handler: ints thread revect +0x28
int 0x28, ax=0x0000
HLT: fcn 0x022c called in HLT block, handler: ints thread revect +0x28
HLT: fcn 0x0233 called in HLT block, handler: ints thread revect +0x2f
INT2F at fc00:0233: AX=1680, BX=0d0f, CX=0004, DX=0003, DS=02a1, ES=02a1
HLT: fcn 0x0233 called in HLT block, handler: ints thread revect +0x2f
HLT: fcn 0x022c called in HLT block, handler: ints thread revect +0x28
int 0x28, ax=0x0000
HLT: fcn 0x022c called in HLT block, handler: ints thread revect +0x28
HLT: fcn 0x0233 called in HLT block, handler: ints thread revect +0x2f
INT2F at fc00:0233: AX=1680, BX=0d0f, CX=0004, DX=0003, DS=02a1, ES=02a1
HLT: fcn 0x0233 called in HLT block, handler: ints thread revect +0x2f
HLT: fcn 0x022c called in HLT block, handler: ints thread revect +0x28
int 0x28, ax=0x0000
```
Are the other candidates I should looking for ?

**Comment by bolle732** [comment] 2016-07-14 06:50
Update:
DOSEmu2 itself does not crash and therefore it won't invoke GDB for a backtrace.

**Comment by bolle732** [comment] 2016-07-14 11:49
Now I've tested Commander Keen 1.4. This works well, no freeze after several minutes. If I get down from 1024x768@16-bit to standard VGA, PC/GEOS is running for 5-10 second and then detects an error and freezes. Unfortunately it doesn't say what exactly happened.

**Comment by stsp** [comment] 2016-07-14 11:54
You need to google about doing 'git bisect'.
First, you do
git tag -l
and walk the list of tags, to find the last that works
good. Then you do 'git bisect' between that and devel.

**Comment by bolle732** [comment] 2016-07-14 12:11
Thank you for the remainder. I have documented this for me.

My problem is, that I don't find any old commit which does not freeze PC/GEOS in `vm86` mode on my Ubuntu 16.04 :( If nothing helps, I would need to return to Ubuntu 15.04 or 15.10.

Therefore, it seems that something other then DOSEmu2 has changed on my system. I'm looking for alternative ways to debug this.

**Comment by stsp** [comment] 2016-07-14 12:12
No, with 'git tag -l' you can go as deep as to dosemu-1.4,
which, you said, works fine. So the method should work in
either case.

**Comment by stsp** [comment] 2016-07-14 12:30
Please don't spend your time on finding other ways
to debug this. Bisect is the best method for newcomers,
you will not find anything better within the reasonable time
frame. Installing and reinstalling older ubuntus will definitely
take more time. Just google out a good instructions and
start bisecting. :) You will need this on many occasions in
the future, too. The ability of doing bisects will really help!

**Comment by bolle732** [comment] 2016-07-14 15:44
I'm running currently a bisect. The hard thing with bisect is, when there are too much commits and the problem has been occurred with more then commit between...

**Comment by bolle732** [comment] 2016-07-14 15:47
Not talking about every time to compare 'dosemu.conf' and 'ems.sys'. But I won't complain, it only needs time. Hopefully will see more tomorrow.

**Comment by stsp** [comment] 2016-07-14 16:28
Grr, what do you mean?
'git bisect' is exactly for bisecting thousands of commits.
Are you doing things correctly? Have you found a good
guidance on 'git bisect'?

> Not talking about every time to compare 'dosemu.conf'

Of course not: just use default dosemu.conf where everything
is commented out.

> and 'ems.sys'

Oh well, in some older dosemus ems.sys can be a problem,
but you may as well exclude it from your config.sys, unless
your prog uses EMS?

**Comment by stsp** [comment] 2016-07-14 16:29
Have you found the git tag that worked the last?

**Comment by stsp** [comment] 2016-07-14 21:38
OK, thanks!
But that's going to be difficult.
I'd need the program to reproduce the problem.

**Comment by stsp** [comment] 2016-07-14 21:40
Also please try $_cli_timeout=(0) in dosemu.conf

**Comment by bolle732** [comment] 2016-07-15 06:22
I've played with `$_cli_timeout = (0)` and different vlaues for `$_pic_watchdog` (still used?). Unfortunately, it didn't help.

I will provide you privately a copy. Will see if I can do that today in my launch break.

**Comment by stsp** [comment] 2016-07-15 07:08
> $_pic_watchdog (still used?). 

Not after the patch in question. :)

> Unfortunately, it didn't help.

Nasty. :(

> I will provide you privately a copy. Will see if I can do that today in my launch break.

Wait, wait.
Firstly, I did have it somewhere, because I remember
I was fixing some EMS problems for it. Secondly, I am
not testing vm86...
So it would be best if you provide me an ssh access for a week-end.

**Comment by bolle732** [comment] 2016-07-15 11:41
Regarding SSH / VNC access I would have to check my notebook first as I should remove a lot of private stuff...
If I had more time at the moment, I would set-up my new notebook and do completely fresh install of Ubuntu 16.04 32-bit on the old one. Then the old notebook could be dedicated for testing VM86 mode.

Do you think we should do it as soon as possible ? Are you planing some bigger changes and would be happy to first sort out the current problem with VM86 ? I'd like to see the benchmark too. But with KVM it works very fine.

**Comment by bolle732** [comment] 2016-07-15 19:09
@stsp 
I've prepared another PC with a new install of Ubuntu 16.04 in 32-bit. All needed to compile DOSEmu2 and the PC/GEOS is ready. How can I send you the information for accessing the system ?

**Comment by stsp** [comment] 2016-07-15 21:07
By e-mail. :)
You don't need to hurry, please use your
spare time the way you like, and thanks for
any contribution.

**Comment by bolle732** [comment] 2016-07-16 09:20
To stsp@users.sourceforge.net ?
I will send the needed info later this day. Need some time to write down the instructions. At the moment, the family needs my attention.

**Comment by stsp** [comment] 2016-07-16 11:33
OK, but be prepared to leave this available
for a few days, because I may not have the
time for that immediately, too.

**Comment by bolle732** [comment] 2016-07-16 14:51
The needed info has been sent. Hope it will help.

**Comment by stsp** [comment] 2016-07-16 17:50
Wow, vnc is so much faster than X port forwarding!

**Comment by stsp** [comment] 2016-07-16 21:28
Fixed in vm86_fix branch.

**Comment by stsp** [comment] 2016-07-17 00:48
OK, I've got it to work.
This is a regression that involves many commits
by different authors (see the log msg for full info),
but I still haven't found the traces of 5ee681a.
So I think there are more regressions involved.
Even though the current fix is good, I suspect it
could work without it.

**Comment by stsp** [comment] 2016-07-17 01:33
@bolle732 could you build the kernel from
git sources? I think we need to fix vm86 in kernel.

**Closed** 2016-07-17 04:00 UTC

**Comment by stsp** [comment] 2016-07-17 04:02
OK, I've finally found the traces of 5ee681a.
The bug is indeed in the kernel and, besides the
dosemu fix, I've also prepared the kernel patches.
I'll upload them here in case you can build the
kernel and test them.

**Comment by stsp** [comment] 2016-07-17 04:05
Kernel patches to test.
Please make sure they compile, do not produce the
compile-time warnings, and work properly with unpatched
dosemu.
[ptch.zip](https://github.com/stsp/dosemu2/files/367671/ptch.zip)

**Comment by bolle732** [comment] 2016-07-17 07:12
Good morning Stas, I see you're very active ;-)

I'll try to test the kernel patch the next days. Sorry, that I can't take the time today.

Current devel is working again with vm86 on my notebook. It's slower then kvm, but that's a story I'll dive into later (need to bisect the exact commit).

dosemu1 / vm86: ~2100 itrs

dosemu2 / kvm: ~2700 itrs
dosemu2 / vm86: ~1600 itrs

Thank you very much for your effort!

**Comment by stsp** [comment] 2016-07-17 09:18
> Good morning Stas, I see you're very active ;-)

Unfortunately.

> It's slower then kvm

That's because I modified your startup script to produce
a lot of logging. Should now be better.
I also now changed your script to not use -n and to not
alter HOME: there are many facilities we provide to not
doing the things like that.
In fact, it would be nice if you stop using custom
config/autoexec too, and use -E/-K options to run your
program from command line, plus setting DOSDRIVE_EXTRA.
If not for anything else, you'll test many features for good
that way.

**Comment by bolle732** [comment] 2016-07-18 05:15
The stats have been from my notebook, System A from issue #205 . Will check the test PC too.

Thank you for the hints regarding my set-up. I know it is a little special. You are free to make a local copy of the program and change it as you desire. For me, I like to have everything in a local directory and be able to simply copy the directory to another machine and start it there.

If this machine would be helpful in the future too, please let me know.

**Comment by bolle732** [comment] 2016-07-18 07:14
I've been trying to build the kernel with your patch, but get a makefile error.
```
scripts/package/Makefile:91: recipe for target 'deb-pkg' failed
make[1]: *** [deb-pkg] Error 2
Makefile:1250: recipe for target 'deb-pkg' failed
make: *** [deb-pkg] Error 2
```
During make, I've seen this compile error:
```
arch/x86/kernel/vm86_32.c: In function ‘do_sys_vm86’:
arch/x86/kernel/vm86_32.c:97:37: error: ‘X86_IF_MASK’ undeclared (first use in this function)
 #define SAFE_OR_MASK (X86_VM_MASK | X86_IF_MASK | X86_EFLAGS_IOPL | \
                                     ^
arch/x86/kernel/vm86_32.c:334:23: note: in expansion of macro ‘SAFE_OR_MASK’
  vm86regs.pt.flags |= SAFE_OR_MASK;
                       ^
arch/x86/kernel/vm86_32.c:97:37: note: each undeclared identifier is reported only once for each function it appears in
 #define SAFE_OR_MASK (X86_VM_MASK | X86_IF_MASK | X86_EFLAGS_IOPL | \
                                     ^
arch/x86/kernel/vm86_32.c:334:23: note: in expansion of macro ‘SAFE_OR_MASK’
  vm86regs.pt.flags |= SAFE_OR_MASK;
                       ^
arch/x86/kernel/vm86_32.c: In function ‘do_set_vflags’:
arch/x86/kernel/vm86_32.c:97:37: error: ‘X86_IF_MASK’ undeclared (first use in this function)
 #define SAFE_OR_MASK (X86_VM_MASK | X86_IF_MASK | X86_EFLAGS_IOPL | \
                                     ^
arch/x86/kernel/vm86_32.c:404:20: note: in expansion of macro ‘SAFE_OR_MASK’
  regs->pt.flags |= SAFE_OR_MASK;
```
I did it as follow:
```
$ cd ~/Development
$ wget https://github.com/stsp/dosemu2/files/367671/ptch.zip
$ mkdir kernel
$ cd kernel
$ git clone git://kernel.ubuntu.com/ubuntu/ubuntu-xenial.git .
$ git tag -l Ubuntu-*
$ git checkout -b dosemu Ubuntu-4.4.0-31.50

$ cp /boot/config-`uname -r` .config
$ yes '' | make oldconfig

$ unzip ../ptch.zip
$ patch -p1 < 0001-vm86-fix-AC-handling.patch
$ patch -p1 < 0002-vm86-fix-flags-returning.patch

$ make clean
$ make -j `getconf _NPROCESSORS_ONLN` deb-pkg LOCALVERSION=-dosemu
```
Compiling without your patch seems to work (it is currently running for 15 minutes or so).

**Comment by bolle732** [comment] 2016-07-18 07:42
The compile without the patch completed successfully on the test PC.

**Comment by stsp** [comment] 2016-07-18 08:20
Hi, thanks for your testing!
New patches are attached.

> I know it is a little special. You are free to make a local copy of the program and change
> it as you desire.

OK, while -n may apply in this case, I would
still encourage you to use dosemu's config/autoexec
unmodified, and if their flexibility is not enough for
your needs - open a feature requests. We should
make them suit for most real-world scenarios.

> If this machine would be helpful in the future too, please let me know.

If there are some further problems with kernel patches
then maybe.

[ptch.zip](https://github.com/stsp/dosemu2/files/368560/ptch.zip)

**Comment by bolle732** [comment] 2016-07-18 11:02
Ok, I've compiled and installed the kernel on the test machine.

Now, I will test the commit a34f32dd321253d7781a5099b0b84ebeb0384c3a .

**Comment by bolle732** [comment] 2016-07-18 11:31
With the patched kernel, PC/GEOS won't startup / switch to the desired graphic mode. Checking `uname -a` shows the version which I've compiled :(

**Comment by stsp** [comment] 2016-07-18 16:52
I'll have to look myself then.
This will have to wait a day or 2.

**Comment by bolle732** [comment] 2016-07-18 17:15
Thanks in advance. As KVM is running fine and currently it is faster, it doesn't hurt. Let me know if I can help further like any problem installing kernel and rebooting the machine.

**Comment by stsp** [comment] 2016-07-18 18:01
I think vm86 can match KVM if we use memcmp
for video mem instead of the protection tricks.
OTOH KVM can use kvm_base, in which case it
will again be unreachable.
Maybe we should indeed stop maintaining vm86
eventually... :(

**Comment by stsp** [comment] 2016-07-18 19:08
> Maybe my checkout of the kernel above didn't worked as I expected.
> Why do I get 4.4.13 instead of 4.4.0-31 ?

Seems because you applied all debian backports.
Would it be possible to use the fresh git kernel instead?

**Comment by bolle732** [comment] 2016-07-18 19:44
Ok, I've used the Ubuntu kernel GIT as I though this would be the right way. If you mean a vanilla kernel, I need to investigate if there's something special for Ubuntu, but it should be possible.

This is a test machine. I've documented the set-up and it should be reinstalled fairly fast. So, it's open for experiments. Maybe I should backup your changes to the start script of PC/GEOS. Simply creating a GZIP and copy away.

**Comment by bolle732** [comment] 2016-07-19 05:32
If there is no advantage in using vm86 regarding kvm, then yes, it would make sense dropping the vm86 support. Especially, if vm86 only complicates the maintaining of the code. But I won't justice, this should be a decision of the real DOSEmu2 devs.

**Comment by andrewbird** [comment] 2016-07-20 11:49
@stsp - Firstly, great work on fixing this issue with vm86. I have had random lockups when using fdisk/format for my older DOS support work. Nothing I could pin down enough to report, but now after your Dosemu2 'feels' so much more solid and responsive!
In principle I'm not opposed to switching to kvm, as I think it's the only long term solution. Yet again there are rumours of i386 distros being discontinued, so I think it's only going to get more difficult to run a 32bit machine. I do think that before vm86 is abandoned kvm should be the default on both i386 and x86_64, so that any issues can be worked through.

**Comment by stsp** [comment] 2016-07-20 11:54
> your Dosemu2 'feels' so much more solid and responsive!

That's really pleasant. :)

> I do think that before vm86 is abandoned kvm should be the default on both i386 and x86_64,
> so that any issues can be worked through.

Yes, likely.
I am planning kvm by default on x86-64 for next -pre,
so the complete switch will have to wait a bit longer.
There are still a lot of kvm-related development in progress.
