### ISSUE TITLE
Fails to find command.com when started in terminal mode (-t)

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#50] opened 2015-07-27 18:48 UTC
This is a strange one. When booting freedos with either X or sdl it completes fine, but if the output is a terminal it fails to find command.com.

![nobootinterm](https://cloud.githubusercontent.com/assets/220835/8914357/b3ced726-3496-11e5-9482-73e6380b546c.png)

See if you can reproduce it, if not I'll send boot.logs

**Comment by PaulRaul** [comment] 2015-07-27 18:55
I had a similar problem to this.  Seems like dosemu didn't like either upper or lowercase filenames on the Linux FS (don't recall which).  I had to change the case of the boot files to make it work.

**Comment by andrewbird** [comment] 2015-07-27 19:04
Thanks, I just tried altering the case, but it didn't change anything for me. What's weird is that it's ok in X or sdl, and only breaks when using the -t switch. I figure it must be some memory overrun somewhere. Thanks anyway.

**Comment by stsp** [comment] 2015-07-27 20:08
Hmm.
Can you try:
$_umb_a0 = (off)
?

**Comment by andrewbird** [comment] 2015-07-27 20:46
yes adding that allowed it to boot to the DOS prompt fine

**Comment by stsp** [comment] 2015-07-27 20:50
Please show your config/autoexec.
In particular I wonder what "UMB's unavailable!"
mean here...

**Comment by andrewbird** [comment] 2015-07-27 21:07
Here you go

autoexec.bat
~~~
@echo off                                                                       
rem autoexec.bat for DOSEMU + FreeDOS                                           
path z:\bin;z:\gnu;z:\dosemu;c:\tc\bin;c:\td                                    
set HELPPATH=z:\help                                                            
set TEMP=c:\tmp                                                                 
blaster                                                                         
prompt $P$G                                                                     
unix -s DOSDRIVE_D                                                              
if "%DOSDRIVE_D%" == "" goto nodrived                                           
lredir d: linux\fs%DOSDRIVE_D%                                                  
:nodrived                                                                       
rem uncomment to load another bitmap font                                       
rem loadhi display con=(vga,437,2)                                              
rem mode con codepage prepare=((850) z:\cpi\ega.cpx)                            
rem mode con codepage select 850                                                
rem ^[chcp 850                                                                  
lredir e: linux\fs/media/cdrom c                                                
unix -s DOSEMU_VERSION                                                          
echo "Welcome to dosemu %DOSEMU_VERSION%!"                                      
unix -e
~~~

config.sys
~~~
rem config.sys for DOSEMU + FreeDOS                                             
rem note that the initial "D:" is set to "Z:" at the end                        
SWITCHES=/F                                                                     
DOS=UMB,HIGH                                                                    
dosdata=umb                                                                     
lastdrive=Z                                                                     
files=40                                                                        
stacks=0                                                                        
buffers=10                                                                      
devicehigh=d:\dosemu\ems.sys                                                    
devicehigh=d:\dosemu\cdrom.sys                                                  
install=d:\dosemu\lredir.com z: linux\fs\${DOSEMU_LIB_DIR}/drive_z ro           
shellhigh=d:\command.com /e:1024 /p
~~~

**Comment by andrewbird** [comment] 2015-07-28 18:36
As a further datapoint I tried dosemu-1.4.0.8 from the ubuntu 14.04 repo with the same config (umb tweak removed) and the same autoexec.bat / config.sys and it booted fine as below. Note the same UMB's unavailable message is there.

![bootinterm-1 4 0 8](https://cloud.githubusercontent.com/assets/220835/8940018/97acb562-355f-11e5-9baf-222755984f25.png)

**Comment by andrewbird** [comment] 2015-07-28 19:27
Also dumb terminal support works ok without the umb tweak

/opt/dosemu2/bin/dosemu -dumb
~~~
ajb@polly:~$ /opt/dosemu2/bin/dosemu -dumb
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory


DOSEMU2 2.0pre3-20150728-gc06270e, configured: 2015-07-28 19:47:59 +0100
Please test against a recent version before reporting bugs and problems.
Submit Bugs & Patches to linux-msdos@vger.kernel.org or via http://dosemu.org.
FreeDOS kernel build 2036 cvs [version Aug 18 2006 compiled Aug 18 2006]
Kernel compatibility 7.10 - WATCOMC - 80386 CPU required - FAT32 support

(C) Copyright 1995-2006 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
UMB's unavailable!                                                             
dosemu XMS 3.0 driver installed.
dosemu EMS driver rev 0.5 installed.
[dosemu cdrom driver installed (V0.2)]
Kernel: allocated 41 Diskbuffers = 21812 Bytes in HMA
Z: = LINUX\FS\ attrib = READ ONLY

FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
Sound on: SB at 0x220-0x22f, IRQ=5, DMA8=1, DMA16=5. MPU-401 at 0x330-0x331.
Redirection for drive D: was deleted.
D: = LINUX\FS/HOME/AJB attrib = READ/WRITE
Error 35 (network name not found)
while redirecting drive E: to LINUX\FS/MEDIA/CDROM
"Welcome to dosemu 2.0pre3-20150728-gc06270e!"
C:\>
~~~

**Comment by stsp** [comment] 2015-07-28 21:16
> Also dumb terminal support works ok without the umb tweak

Should now be fixed.

**Comment by andrewbird** [comment] 2015-07-28 22:59
Mmm not sure there was anything wrong with -dumb mode before, but now things are wrong

1/ dosemu -dumb
starts in existing terminal, and will scroll etc, which is correct. But now has my can't find command.com problem, but it was OK before (maybe this is a clue?)

2/ dosemu -t
a) this now either an X or SDL window (I can't tell the difference) whereas it should be run in the terminal using slang/curses
b) if I unset DISPLAY I get
~~~
 ERROR: You do not have the DISPLAY variable set, but want to run DOSEMU
in its own X-window. Set the DISPLAY variable such as

    DISPLAY=:0.0; export DISPLAY

if running X locally or

    DISPLAY=host:0.0; export DISPLAY

when running remotely ('host' being the machine where you are typing at)

After this run xdosemu again.
Segmentation fault (core dumped)
~~~

3/ dosemu -X
if DISPLAY is unset I get error message and segfault as above

4/ dosemu -S
if DISPLAY is unset I get error message
~~~
ERROR: SDL init: Failed to connect to the Mir Server
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
ERROR: Unable to open console or check with X to evaluate the keyboard map.
Please specify your keyboard map explicitly via the $_layout option.
Press ENTER to continue with DOS programs thinking that they use a US layout or
Ctrl-C to exit.
~~~

**Comment by stsp** [comment] 2015-07-29 21:41
Sorry for that.
Could you please re-check?

**Comment by andrewbird** [comment] 2015-07-30 08:03
Hi,
Things are looking better now

video|DISPLAY=:0|unset DISPLAY
-------|---------------|-------------------
-dumb|OK|OK
-t|OK|OK
-X|OK|SEGV
-S|OK|OK

Here's the SEGV from the -X with DISPLAY unset
~~~
$ /opt/dosemu2/bin/dosemu -X
ERROR: You do not have the DISPLAY variable set, but want to run DOSEMU
in its own X-window. Set the DISPLAY variable such as

    DISPLAY=:0.0; export DISPLAY

if running X locally or

    DISPLAY=host:0.0; export DISPLAY

when running remotely ('host' being the machine where you are typing at)

After this run xdosemu again.
Segmentation fault (core dumped)
~~~

**Comment by stsp** [comment] 2015-07-30 18:33
Thanks, should now be better.

**Comment by andrewbird** [comment] 2015-07-30 19:01
Good, the display issues are fixed.
-dumb, -t, -X, -S with DISPLAY set are OK
-dumb, -t, -X, -S with DISPLAY unset are OK

Any thoughts as to why dosemu2 either -dumb, or -t, can't find command.com, but dosemu 1.4.0.8 can?

**Comment by stsp** [comment] 2015-07-30 19:39
$_umb_a0 is dosemu2-specific, it doesn't exist
at all in dosemu1. So comparison is impossible,
and more investigations are needed to find out
why it breaks.

**Comment by andrewbird** [comment] 2015-07-30 19:57
So have you been able to reproduce the issue, using my config.sys/autoexec.bat?




Sent from Samsung tablet

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 30/07/2015  20:39  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk> 
Subject Re: [dosemu2] Fails to find command.com when started in terminal mode
  (-t) (#50) 
 
$_umb_a0 is dosemu2-specific, it doesn't exist
at all in dosemu1. So comparison is impossible,
and more investigations are needed to find out
why it breaks.

**Comment by stsp** [comment] 2015-07-30 19:59
So far haven't tried due to the life constraints.
I'll let you know.

**Comment by stsp** [comment] 2015-07-31 20:08
Yes, I indeed can reproduce this.

**Comment by stsp** [comment] 2015-07-31 20:10
UMBs unavailable is because you try to
devicehigh the ems.sys. It creates umbs
and should not be loaded high.

**Comment by stsp** [comment] 2015-07-31 21:58
It seems there is a FreeDOS bug.
Everything works fine with other DOS, and
google points to this:
http://comments.gmane.org/gmane.comp.emulators.freedos.kernel/316
"Unfortunately, this version reboots
on my machine when command.com tries to load."

I wonder if you can raise this to freedos ppl.

**Comment by stsp** [comment] 2015-07-31 23:31
I've filled an upstream report:
https://sourceforge.net/p/freedos/bugs/133/

**Comment by andrewbird** [comment] 2015-08-01 17:38
Thanks for both filing the bug with FreeDOS and applying the workaround that fixed it for me.

**Comment by stsp** [comment] 2017-09-26 01:41
This seems to have been fixed by 6ce27a6.

**Comment by stsp** [comment] 2017-09-26 01:47
So on current devel it can be reproduced with:
```
$_umb_a0 = (on)
$_ems_frame = (0xe400)
```

**Comment by stsp** [comment] 2017-09-26 01:54
Better reproducer:
```
$_umb_a0 = (on)
$_ems = (off)
```
umb.sys must be loaded.

**Comment by stsp** [comment] 2018-12-07 01:19
Should now be fixed in fdpp.
freedos-specific work-around disabled.

**Comment by stsp** [comment] 2018-12-20 01:56
Seems to still break if EMS is disabled.

**Comment by stsp** [comment] 2018-12-23 01:41
Should now be fixed again, this time
even with EMS enabled.

**Closed** 2018-12-23 01:42 UTC
Labels: bug
