### ISSUE TITLE
dosemu2 (x). Doom 2 and Rise of the Triad nets about 10 FPS

### ISSUE THREAD

**Issue by mikedebian** [stsp/dosemu2#403] opened 2017-07-01 19:24 UTC
OpenSuse Tumbleweed
Mesa 17.2 dev
Ryzen 1800X
Stock config

Doom 2 and Rise of the Triad gets about 5-10 FPS in game (and demo).
Menu takes a while to register keystrokes. Choppy sound effects and music.

SW3D and games like DN3D runs excellent.

**Comment by stsp** [comment] 2017-07-01 23:52
How do you measure fps?
I see that sound in doom2 is a bit
choppy (but compare it to dosemu1
to see how choppy it was). But I
can't justify your 5fps claim.

**Comment by mikedebian** [comment] 2017-07-02 11:05
Have a look. Fullscreen makes no difference.

[Take a look for yourself](https://www.dropbox.com/s/1ce0du0qcn26hby/dsa.mp4?dl=0)

Video is screenrecorded MP4.

**Comment by stsp** [comment] 2017-07-03 19:21
I can only reproduce this with full-screen.
Try
`dosemu -w -X`
that seems to work better.
Also setting `$_SDL_swrend = (off)`
in dosemu.conf seems to help.

**Comment by mikedebian** [comment] 2017-07-03 20:17
No change, sorry. Do you need debug info again, or do you take it from the other issue you fixed?

**Comment by stsp** [comment] 2017-07-03 21:21
In full-screen mode the problem is now fixed.

**Closed** 2017-07-03 21:20 UTC
