### ISSUE TITLE
Commander Keen 4 and 5 (v1.4) hang after a while when you let them play their demo with KVM with 'Fix jerky motion' enabled in the game's configruation

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#194] opened 2016-06-10 21:38 UTC
To reproduce, run Commander Keen 4 version 1.4 and let it play its demo. At one point or another, it will just hang.

I could not reproduce this with cpuemu or Commander Keen 5. Version 1.0 of the game does not initialize in dosemu.

The different versions of the game can be found here:
http://www.shikadi.net/keenwiki/Keen_4_Versions

**Comment by jschwartzenberg** [comment] 2016-06-10 21:43
The hang can also occur while just playing, but it seems to take significantly longer to occur then.

**Comment by bolle732** [comment] 2016-07-13 20:43
As I needed a reference for another test I've tried Commander Keen 1.4 on my 32-bit Ubuntu 16.04 with the current `devel` (a34f32dd321253d7781a5099b0b84ebeb0384c3a). The demo has been playing for more then 10 minutes without a hang using KVM.

**Comment by stsp** [comment] 2016-07-18 10:39
This needs to be re-tested with the current updates.

**Comment by jschwartzenberg** [comment] 2016-07-18 20:15
This still occurs here. I'm on 64-bit Ubuntu 16.04.

**Comment by bolle732** [comment] 2016-07-21 05:47
I've tested with DOSEmu2 13b6e8f3fccd20d212421159fca3b17b18f55501 and KVM. OS is Ubuntu 16.04 LTS 64-bit with Kernel is 4.4.0-31-generic.

The demo plays fine. There is only sometime like a line in the graphics which isn't drawn correctly. After 10 minutes, the demo is still playing.

**Comment by jschwartzenberg** [comment] 2016-07-21 07:26
Is easily hangs within 10 minutes here, so it seems like a difference between our setups is the cause.

Should I provide you with my drive_c or maybe you could provide me (an undressed version) of yours?

**Comment by bolle732** [comment] 2016-07-21 07:59
I will send you my version by mail.

**Comment by bolle732** [comment] 2016-07-21 09:10
Ok, haven't found your email address here on Github... So, I've attached the file here. Extract it and run the "start.sh" script inside the folder "KEEN4".

[KEEN4.zip](https://github.com/stsp/dosemu2/files/375542/KEEN4.zip)

**Comment by jschwartzenberg** [comment] 2016-07-22 18:35
Yep your version runs fine here! I'll have to figure out the differences between our version now...

**Comment by jschwartzenberg** [comment] 2016-07-22 18:44
It seems it's due to my configuration. If you use this file to your version, it will also hang.
[config.ck4.zip](https://github.com/stsp/dosemu2/files/378856/config.ck4.zip)

**Comment by bolle732** [comment] 2016-07-22 21:58
Yes, even on my 32-bit Ubuntu, with your file I get the freeze / hang.

So, are this file from different versions ? Or could your file be corrupted and accidentally produce an endless loop or something similar ?

**Comment by stsp** [comment] 2016-07-23 00:13
So since this is not a dosemu problem, I am closing.
You can still discuss the differences and find the root
of the problem.
Thanks for everyone involved! Luckily I don't have to
reproduce this myself now, which is more than welcome. :)

**Comment by jschwartzenberg** [comment] 2016-07-23 07:15
But it is a KVM problem. It works fine with my configuration without kvm in dosemu and in other emulators such as dosbox.

I suspect I changed the video options and it's a problem with the interaction between vgaemu and kvm again.

**Comment by jschwartzenberg** [comment] 2016-07-23 10:00
I could reproduce it with Commander Keen 5 as well now. The problem occurs when you enable "Fix jerky motion" in the configuration.

While the bug is a bit more complex to reproduce, this is definitely a bug in dosemu.

**Comment by stsp** [comment] 2016-07-23 12:50
Is it the same option in both games?
So does anyone think I should disable KVM
by default for pre6 too, or is it a too small bug?

**Comment by jschwartzenberg** [comment] 2016-07-23 14:58
Yes, both have this option. Probably 6 has the same. I think we should test more with KVM.

**Comment by jschwartzenberg** [comment] 2016-07-24 20:38
Some notes about the game that are unrelated to this bug:

Note that there is also a CGA version of the game. While the VGA/(EGA?) version has jerky scrolling issues in dosemu (even when that fix option worked), the CGA version does not have such problems at all.

(The only vga emulation that supports scrolling in this game correctly is the one in dosbox. The one in VMware, VirtualPC, VirtualBox, etc. also gives jerky scrolling with this game.)

Would it make sense to test direct VGA access in combination with KVM significantly? I haven't tested it at all so far, but for some hard to emulate programs like this one it's really nice.

**Comment by stsp** [comment] 2016-07-24 21:28
Why not?
Direct VGA access is tested very poorly these days.

**Comment by sulix** [comment] 2019-08-26 00:27
I haven't had a chance to test this myself, but I can shed some light on the "Fix Jerky Motion" feature, and hazard a guess as to why it might not be working.

Basically, each frame, Keen normally waits for the "end of the frame" before updating the CRTC start and horizontal PEL panning registers. (This is basically to avoid tearing by double buffering and swapping the buffers).

Keen's definition of "end of frame" is "a sufficiently long period where the display is disabled, but the vertical retrace hasn't started". What "Fix Jerky Motion" does is _increase_ how long this period needs to be. This is possibly because some EGA/VGA cards had particularly long horizontal blanking periods (or sufficiently fast I/O register access) that Keen would mistake an HBlank for the end of the frame, and cause tearing.

Now, if the opposite happens, and there are no long enough periods of DD=1, VRETRACE=0, then Keen would normally hang here. Instead, as a backup, it uses the PIT timer (in the game's sound subsystem) to limit the amount of time spent waiting to 3 frames (@ 70Hz). It does this by periodically enabling and disabling interrupts to let the timer IRQ occur.

This hang could potentially occur, therefore, if the following things are true:
1. The dosemu2 VGA emulation is giving a long enough period of DD=1, VRETRACE=0 for the non-"fix jerky motion" mode, but not enough for the "fix jerky motion" mode.
2. The KVM backend doesn't trigger interrupts properly if they're only enabled very briefly. Keen only runs one instruction with the interrupts enabled — a jmp $+2 — which may not be long enough for the timer IRQ to be properly emulated and occur.

Note that Keen Dreams, CKSRCMOD, and Omnispeak currently don't use this way of searching for the end of frame, so this probably isn't reproducible there (they also therefore don't have a "fix jerky motion" option). Wolfenstein 3d has [some similar code](https://github.com/id-Software/wolf3d/blob/master/WOLFSRC/ID_VL_A.ASM) (though without the "fix jerky motion option — imagine a few more copies of that "in" loop. It also has a few other minor changes/fixes, but is probably at least slightly useful.

And [here's](https://davidgow.net/stuff/vw_setscreenwait.asm) a disassembly of the actual code (note that the offsets won't match a released version, sorry).

**Comment by stsp** [comment] 2019-08-26 09:24
Thanks, the "if enabled very briefly"
suspection must be very interesting.
Other backends enable the interrupts
immediately after STI, and all pending
interrupts should go in. But KVM is
likely giving the 1 instruction hold-off,
so that interrupts are enabled one
instruction later. If there is cli immediately,
maybe we fsck.
But to check that, I'll need a way to
reliably reproduce the problem, which
seems to be quite difficult right now.

**Comment by stsp** [comment] 2019-08-29 13:21
No, that doesn't seem to be a problem.
With a simple test-case:
```
sti
cli
jmp 0
```
I can see that the interrupts coming in KVM
mode even w/o `jmp` in between of stil and cli,
so it doesn't give the extra interrupt hold-off.
So now I started keen4 1.4, enabled "fix jerky
motion" and some "svga compatibility" and am
waiting for a hang in demo. Seems to not hang.

**Comment by stsp** [comment] 2019-08-29 13:30
And if I use the exe provided here by @bolle732 
and config by @jschwartzenberg then there is a
hang indeed! But its not a problem with interrupts
because the music is still playing. Only video hangs.

**Comment by stsp** [comment] 2019-08-29 13:52
But still, it hangs in exact that code.
If I nop out all `jnz     short ReRunInts`
then it unfreezes and continues.

**Comment by stsp** [comment] 2019-08-29 14:19
I enlarged the hretrace.
Seems to work fine now.

**Closed** 2019-08-29 14:19 UTC

**Comment by jschwartzenberg** [comment] 2019-08-30 19:56
Is it possible that the KVM issue in prince2 is also resolved with this fix? See #290. I hope I can test this soon.

**Comment by stsp** [comment] 2019-08-30 20:14
Very unlikely as keen just happened to have
the crazy code.
