### ISSUE TITLE
Apparent problem with dates

### ISSUE THREAD

**Issue by RossBoylan** [stsp/dosemu2#761] opened 2019-01-21 22:51 UTC
**Describe the bug**
Running Managing Your Money (MYM) under dosemu2 tends to show a lot of dates as 1/00/1900.
In many cases this appears to be a display issue only; for example, a field will show a proper date and then, as I move out of it, it shows as 1/00/1900 (the 00 is not a placeholder--that's literally what it shows).  But if I keep going, the transaction will later show as the correct date.

I think I've had some cases where the 1900 date replaces the date I've entered.

MYM is a full screen application with a keyboard based interface.  It has limited mouse support as well, i.e., you can use the mouse to select menu items.  It's not graphical the way a game would be; it appears to be at a level similar to curses.

At first I thought this might be a 2019 problem, since the program is pre-Y2K (though it has handled years to 2018 OK).  But when run under dosbox this problem does not appear.

Comment: this might be an issue in fdpp or comcom32 rather than dosemu2 *per se*.

If I type date at the DOS prompt it responds with today's date.

**To Reproduce**
In most cases the field must have focus and then you must move out of it.
This is true even if you have done nothing to change the field.
On startup, 1/00/1900 shows as the date (before any input).  I reset that to my desired date, 12/31/2018.

**Binaries**
Proprietary software, and so best if I don't attach.
Here's a screenshot showing the problem on startup: 
![mym1900](https://user-images.githubusercontent.com/2514994/51502388-bd4ad080-1d8a-11e9-985b-5a6ab4756202.png).

**Log**
Let me know if you want particular debugging enabled.  I started dosemu2, invoked the program, and exited.  Here's the 
[boot.log](https://github.com/stsp/dosemu2/files/2780708/boot.log).

**Comment by stsp** [comment] 2019-01-21 23:32
Would be good to see if it is not
an fdpp problem. For this you need
to put freedos's kernel.sys to
`~/.dosemu/drive_c`
and freedos will boot.

**Comment by RossBoylan** [comment] 2019-01-22 05:47
Same result with freedos using KERNL86.SYS, but **KERNL386.SYS seems to work properly.**

Since I'm not sure I did what you intended, here are the steps

1. Looked for kernel.sys in the freedos source and didn't find it.  Did find a directory named kernel that appeared to have source files and concluded it is a result of the build process.
2. freedos is not packaged for Debian.
3. Downloaded the freedos 1.2 iso installer and loop mounted it.
4. Extracted KERNL86.SYS and KERNL386.SYS from a KERNEL.ZIP file in the installer.
5. Copied KERNEL86.SYS to KERNEL.SYS on .dosemu/drive_c.
6. Started dosemu.  The window that opens reports FreeDOS kernel 2042 and the warnings I had been getting about fdpp and command.com do *not* appear.  So I believe I got dosemu2 to use FreeDOS.
7. Start MYM; today's date still shows as 1/00/1900.  date at the command prompt returns 01-21-2019.
8. Exit MYM/dosemu and copy KERNEL386.SYS over .dosemu/drive_c/KERNEL.SAS
9. Start dosemu.  `date` at command prompt still works properly.
10. Start MYM.  _Today's date now shows  properly!_  I went into some later screens to see if the "converts to 1/00/1900 on leaving the field" behavior continues; it seems not to.

Tangentially related observations/questions:

BTW, dosemu2 runs quicker and uses less CPU than dosbox.  Is that a hardware vs software emulation difference?

How come command.com isn't part of freedos, or at least part of fdpp?

**Comment by stsp** [comment] 2019-01-22 06:50
What you did sounds right, but
finding the problem in one freedos
kernel and not in another looks odd.
You could try the kernel from
dosemu-freedos-1.0.tgz that comes
with dosemu1.
Using 386 kernel is safe (still realmode),
but of course it is better to have the
bug fixed.
dosemu can be tuned for speed vs
cpu usage with `speed` command
that takes the number as argument.
The more the number is, the higher
is the cpu usage and faster speed.
But 0 is the highest number meaning
burn all cpu. If you want to change
that at boot, use `$_hogthreshold`
setting in .dosemurc. You can also
set `$_cpu_vm = “emulated"` to
compare the software emulation
with dosbox. I believe dosbox also
has the tuning knobs, so the default
setup comparing is likely not productive.
freecom is part of freedos for sure.
Since you already downloaded freedos,
you can as well extract freecom
from there and replace our comcom32.
But freecom is not the best command.com
in the world, so you may get problems.
comcom32 models after the 4dos.com
behaviour.

**Comment by bolle732** [comment] 2019-01-22 08:01
Could the ```$_timemode``` settings have an effect here ?

Personally, I ues ```$_timemode = "linux"```, because otherwise my program don't has the right time after the notebook wakes up from sleep.

Maybe completely unrelated.

**Comment by stsp** [comment] 2019-01-22 08:21
Worth a try, but I dont think so.
Timemode allows to avoid the clock
scew, but not all zeros in the date.

**Comment by andrewbird** [comment] 2019-01-22 13:18
I tested(observed the splash screen on startup) MYM v12 (is on winworldpc.com)

#### 32bit with hardware vm86() (so no emulation)
- MS-DOS 6.22
  - last used and current date is fine (with timemode set to any of pit, linux or bios)
- FreeDOS 1.20
  - last used and current date is fine (with timemode set to any of pit, linux or bios)
- FDPP from git
  - last used and current date is fine (with timemode set to any of pit, linux or bios)

#### 32bit with various emulation
I noticed from your log you are on 64bit and have no kvm so I tried emulation on my 32bit (vm86, full, vm86sim, fullsim) and all behave properly at the splash screen.

So I don't think I can reproduce this here.

**Comment by stsp** [comment] 2019-01-23 14:27
Closing then, until a better reproducer.

**Closed by stsp** 2019-01-23 14:27 UTC

**Comment by RossBoylan** [comment] 2019-01-23 18:45
@stsp I downloaded dosemu-freedos-1.0.tgz  from the dosemu1 site and extracted dosemu/freedos/kernel.sys over the .dosemu/drive_c/KERNEL.SYS.  It had the same 1/00/1900 date problem.  *However* when I restored the KERNL86.SYS (with name change) that I used before, for the current FreeDos installation CD, the date showed properly.  I closed everything and restarted, and the date showed incorrectly.  I tried at least 2 or 3 more times, and it was wrong each time.

@bolle732 Then, with the KERNL86.SYS version still in place, I created ~/.dosemu/.dosemurc (@stsp should that be effective?) and set `$_timemode = "linux"`.  It didn't help; I tried a couple of times.

Restoring the KERNL386.SAS from the FreeDos installation CD restored the proper date behavior.

@andrewbird That's interesting you don't see this problem.  I'm using dosemu2 git development branch, fdpp git master branch, and command.com from @stsp.  Those sound pretty close to what you did.  However, I'm running under 64 bit VirtualBox 4.  Maybe it's some interaction with that?

**Comment by stsp** [comment] 2019-01-23 19:50
dosemu2 under vbox? Wtf? :)

**Comment by stsp** [comment] 2019-01-23 20:52
VM is running on what? Are you using
some kind of hosting? In this case maybe
you can try other VMs. vmware, qemu.

**Comment by RossBoylan** [comment] 2019-01-23 21:20
It's all running on my machine.  64 bit Debian GNU/Linux is the host.  At least for VirtualBox and KVM I think I have to pick: I can run one or the other, but not both at once.

________________________________________

**Comment by stsp** [comment] 2019-01-23 21:24
So why can't you run on host?
dosemu2 can work w/o KVM if you want
to spare KVM for something else (though
I barely understand what you say)

**Comment by RossBoylan** [comment] 2019-01-23 21:58
The host is running older software, and I don't know if it's what dosemu2 needs--particularly  the version I built on the VM.

I was running dosemu1 on the host.
Ross

________________________________________

**Comment by stsp** [comment] 2019-01-23 22:09
dosemu2 tries to compile-time check
the needed components and disable
whatever is inappropriate. While this
can't be 100% reliable, the chances
are good that if you build dosemu2
on host, it will somehow work. Maybe
not very reliably, maybe even w/o DPMI
support, w/o SDL, sound, network, whatever,
but the test with date should be performed.
System requirements in INSTALL are
about fully functional dosemu2. If you
only need to perform some test, you don't
need it fully functional, so you can try to
violate the requirements.
