### ISSUE TITLE
LASTDRIVE and lredir2 in fdconfig.sys not working

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#562] opened 2018-02-15 23:40 UTC
````
dosemu2-git 2.0pre8.94.g2a0d2f654-1

fdconfig.sys
lastdrive=Z
install=d:\dosemu\lredir2.com z: \\linux\fs\${DOSEMU_LIB_DIR}/drive_z ro
````

Neither of these lines are working. lredir2 in fdconfig doesn't seem to work any more and lastdrive is being ignored. At the prompt I can lredir to `f:` but not `g:`.

It is necessary to lredir in fdconfig because command.com doesn't work properly when the drive it was loaded from disappears.

**Comment by stsp** [comment] 2018-02-15 23:47
There is no such line in fdconfig.sys since
commit bee9ae96b, which is 2 years ago.
I can't provide any compatibility with 2 years
old setups, sorry. In the future I'll come up
with the solution to this problem, so that I
can change fdconfig.sys behind user's back.
But for now I can't do that, so please update.

**Comment by severach** [comment] 2018-02-15 23:50
I don't run the default fdconfig.sys. It isn't even close to functional. I need the DOSEMU drive to be Z:, not the next drive up.

`lastdrive` is broken too.

**Comment by stsp** [comment] 2018-02-15 23:57
Use `lredir2 z: c:` to move C: to Z:.
Old syntax will soon be disabled (still
available via lredir.com for a short while)

**Comment by severach** [comment] 2018-02-16 02:31
That must be a planned feature. It doesn't work yet. "Invalid Argument"

At this point lredir and lredir2 are so broken that they can't redirect anything anywhere.

**Comment by stsp** [comment] 2018-02-16 11:08
No, that works perfectly, both from
fdconfig.sys (if emufs.sys is loaded)
and from autoexec.bat (in this case
even w/o emufs.sys).
The following fdconfig.sys works:
```
rem config.sys for DOSEMU + FreeDOS^M
SWITCHES=/F^M
DOS=UMB,HIGH^M
dosdata=umb^M
lastdrive=Z^M
files=40^M
stacks=0^M
buffers=10^M
device=e:\dosemu\umb.sys^M
devicehigh=e:\dosemu\ems.sys^M
devicehigh=e:\dosemu\emufs.sys^M
install=e:\dosemu\lredir2.com z: c:^M
shellhigh=c:\command.com /e:1024 /p^M
```

**Comment by severach** [comment] 2018-02-16 23:04
2a0d2f654
````
rem config.sys for DOSEMU + FreeDOS
SWITCHES=/F
DOS=UMB,HIGH
dosdata=umb
lastdrive=Z
files=100
stacks=0
buffers=10
device=d:\dosemu\umb.sys
devicehigh=d:\dosemu\ems.sys
rem devicehigh=d:\dosemu\cdrom.sys
devicehigh=d:\dosemu\emufs.sys
rem install=d:\dosemu\lredir2.com z: linux\fs\${DOSEMU_LIB_DIR}\drive_z ro
shellhigh=d:\command.com /e:1024 /p
````

````
D:\dosemu>lredir2
Current Drive Redirections:
C: = \\LINUX\FS\home\chris\.dosemu\drives\c\ attrib = READ/WRITE
D: = \\LINUX\FS\home\chris\.dosemu\drives\d\ attrib = READ/WRITE
E: = \\LINUX\FS\usr\share\dosemu\dosemu2-cmds-0.1\ attrib = READ/WRITE
cwd: /home/chris/.dosemu/drives/d/DOSEMU
 
D:\dosemu>lredir2 Z: C:
Error f (invalid drive) while redirecting drive Z: to \\LINUX\FS\HOME\CHRIS\.DOS
EMU\DRIVES\C\
 
D:\dosemu>lredir2 z: c:
Error f (invalid drive) while redirecting drive Z: to \\LINUX\FS\HOME\CHRIS\.DOS
EMU\DRIVES\C\
 
D:\dosemu>lredir2 f: c:
F: = \\LINUX\FS\HOME\CHRIS\.DOSEMU\DRIVES\C\ attrib = READ/WRITE
 
D:\dosemu>lredir2 g: c:
Error f (invalid drive) while redirecting drive G: to \\LINUX\FS\HOME\CHRIS\.DOS
EMU\DRIVES\C\
````

**Comment by stsp** [comment] 2018-02-16 23:30
Yes, this looks like `LASTDRIVE` is not working
for you, but I tried your config and it works fine.
I wonder why you have dosemu tools on D:.
They are likely not up-to-date, hence the problems.
The point of having them on E: is that they are
then always up-to-date.
However, dosemu should check their version
and refuse to load them, which is quite visible
on boot, so I am not sure if this is your problem.
If your tools are not up-to-date, back them up
and see which one actually caused this.

**Comment by severach** [comment] 2018-02-16 23:38
They aren't out of date. lredir is lying. The drive it says is mapped isn't.
````
D:\>dir
 
 Volume in drive D is mu/drives/d
 Directory of D:\
 
CPI            <DIR>        02-16-18  6:35p cpi
DOC            <DIR>        08-23-17  2:49p doc
DOSEMU         <DIR>        02-16-18  6:35p dosemu
NLS            <DIR>        02-16-18  6:35p nls
MTCP     CFG            16  07-07-11  5:35a mtcp.cfg
KERNEL   SYS        45,344  06-21-11 11:39p kernel.sys
BIN            <DIR>        02-16-18  6:35p bin
HELP           <DIR>        02-16-18  6:35p help
AUTOEXEC BAT           473  10-29-13  9:05p autoexec.bat
TMP            <DIR>        02-16-18  6:08p tmp
CONFIG   SYS           350  11-12-06  6:05p config.sys
COMMAND  COM        66,945  08-28-06 10:38p command.com
APPINFO        <DIR>        02-16-18  6:35p appinfo
GNU            <DIR>        02-16-18  6:35p gnu
         5 file(s)        113,128 bytes
         9 dir(s)       29,438.00 MB free
D:\>E:
 
E:\>dir
 
 Volume in drive E is u2-cmds-0.1
 Directory of E:\
 
DOSEMU         <DIR>        02-16-18  6:35p dosemu
FDCONFIG SYS           247  02-15-18  9:28p fdconfig.sys
AUTOEXEC BAT           638  02-15-18  9:28p autoexec.bat
AUTOEMU  BAT           561  02-15-18  9:28p autoemu.bat
CONFIG   SYS           529  02-15-18  9:28p config.sys
         4 file(s)          1,975 bytes
         1 dir(s)       29,438.00 MB free
````

**Comment by stsp** [comment] 2018-02-17 11:43
Andrew, Julius, can you help making
some sense ouf of this? Is anything
broken?

**Comment by jschwartzenberg** [comment] 2018-02-17 16:25
Maybe it would be good to provide an example root? I don't fully understand what's going on either.

**Comment by stsp** [comment] 2018-02-17 16:30
lredir2 works for you properly, right?

**Comment by jschwartzenberg** [comment] 2018-02-17 16:36
I didn't test it recently, but in general it always works.

**Comment by stsp** [comment] 2018-02-17 16:37
I changed it so it could break.

**Comment by severach** [comment] 2018-02-17 23:44
dosemu is a package for me. It is not possible to have old binaries.

ac0722af83e fully working
2066d1037 breaks the shell line with ${DOSEMU_LIB_DIR}
14ac7abbe5 breaks LASTDRIVE

DOSEMU does not control LASTDRIVE so it's probably not broken. lredir2 isn't reading it right.

**Comment by stsp** [comment] 2018-02-18 00:03
> 2066d10 breaks the shell line with ${DOSEMU_LIB_DIR}

It is still available via `lredir.com`.
But may be disabled in the future.

**Comment by stsp** [comment] 2018-02-18 13:54
@andrewbird confirms some problems.
Now the interesting question is why I don't
see them...

**Comment by stsp** [comment] 2018-02-18 16:32
I re-enabled the old syntax in lredir2 for now.

**Comment by stsp** [comment] 2018-02-18 22:13
Could you check LASTDRIVE problem w/o emufs.sys?

**Comment by andrewbird** [comment] 2018-02-20 17:12
@stsp, I have a patch coming, just testing now. But it seems the difference between your setup and mine is that it doesn't crash on 64bit, but does on 32bit.

**Comment by stsp** [comment] 2018-02-20 17:14
What problem have you reproduced?
This one or another crash you mentioned?

**Comment by andrewbird** [comment] 2018-02-20 17:26
Both are related

**Comment by stsp** [comment] 2018-02-20 17:36
Cool, many thanks for taking this up!

**Comment by andrewbird** [comment] 2018-02-20 21:09
Still having some probs with CDS corruption on older DOS versions (<= 3.21), so I'll work on this again tomorrow.

**Comment by stsp** [comment] 2018-02-21 09:07
Just wondering, what causes the corruption?
Too early redirect_devices()? But w/o emufs.sys
that shouldn't happen...

**Comment by andrewbird** [comment] 2018-02-24 18:03
The reason I see problems with MS-DOS < 3.3 is that dos_post_boot() is hung off the int2f/ae00 function which only exists on DOS >= 3.30, so switching the redir_it() call back to a similar method to before fixes that. But there are still problems with CDS.
Locally I rewrote things here to get the specific CDS directly from DOS (int2f/1217) rather than use the CDS array, which works quite nicely. However I notice that if the redir_it() happens early such as first DOS function call (usually the open of config.sys) or by use of emufs.sys, then the CDS changes made are not copied to the resized and relocated CDS upon close of config.sys. This is evident by upon close of config.sys access is made to fatfs instead of mfs. I suspect that @severach is seeing this effect when he mentions that lastdrive makes no difference and that DOS is actually accessing the drive underneath rather than that shown by lredir.
So I'm looking for ideas
- we could revert to the method that was used before, namely chasing the CDS around via calculate_pointers() and calling redir_it() multiple times.
- we could find a way to delay on how to delay redir_it() until after config.sys is processed.
  - I once suggested watching for open of command.com, but you rightly pointed out that command processor might not be command.com (I think 4DOS was the use case)
  - I wonder if we could watch for close of config.sys, then redir_it() on first open

Thoughts?

**Comment by stsp** [comment] 2018-02-25 11:16
> The reason I see problems with MS-DOS < 3.3

I guess you see the problem _only_ with DOS<3.3?
Then this is not the problem @severach is seeing.

> I suspect that @severach is seeing this effect when he mentions that lastdrive makes no difference

No because he isn't using DOS<3.3 and so post_boot()
should work for him. Practice shows he uses the default
setups in most cases, with altered config/autoexec.
I don't think the problem exist in the default setup or
someone would already notice it.

> we could find a way to delay the call of redir_it() until after config.sys is processed.

This way is called post_boot().

> Thoughts?

You've yet to check what DOSes move CDS losing
its content in a process. Plus the problem you refer to, seems <3.0.

**Comment by stsp** [comment] 2018-02-26 14:33
Actually I wonder if maybe this is a post_boot()
problem, which probably doesn't activate in some
case.
Andrew, do we see something similar to this bug
report if the post_boot() is forcibly disabled?

**Comment by severach** [comment] 2018-03-07 00:14
Found it! I have some large files in `C:\`. `lredir2 z: c:` stops working when the sum of the filesizes >2GB. If those same files are placed into `C:\AnyFolder\` `lredir2` doesn't break.

Create a 1.5GB file and a 1.0GB file. Try with neither, one, or both files in C:\. I also have some 32GB files. Those in C:\ are instant breakage.

**Comment by stsp** [comment] 2018-03-07 08:30
Interesting observation.
Please open a separate ticket for the file sizes.

But then I don't understand what does this have
to do with LASTDRIVE. Are those large files only
break lredir2 for drivers above E:?

**Comment by severach** [comment] 2018-03-07 09:43
Turns out it doesn't. `LASTDRIVE` isn't controlled by `dosemu` so can't be broken. Something is wrong in `lredir2`. I've had those files in `C:\` all along. Commit 14ac7ab broke `lredir2` so it couldn't handle a `C:\` with big files unless the drive <= F. Move them to where `lredir2` can't see them and all drive letters work again.

`lredir2` didn't break for you because you don't have 98GB of files in `C:\`, or 8GB as DOS sees it.

**Comment by stsp** [comment] 2018-03-07 09:51
OK, so you say that lredir2 can map drives with
large files only if the destination drive is <=F.
The source drive doesn't matter as well as the
LASTDRIVE.
That's an interesting observation which must be
checked.
Andrew, what do you think?

**Comment by severach** [comment] 2018-03-07 10:39
Clearly more testing is needed. I just started a brand new ~/.dosemu and it works with bunches of large files.

````
dd if=/dev/zero of=file4097 bs=1M count=4097
````

````
C:\>dir
 Volume in drive C is mu/drives/c
 Directory of C:\
 
FILE4097         1,048,576  03-07-18  5:32a
KERNEL   SYS        45,344  06-21-11 11:39p
TMP                  <DIR>  03-07-18  5:17a
FDCONFIG SYS           247  03-07-18  5:16a
FILE2047        2,146,435,072  03-07-18  5:24a
FILE2048        2,147,483,648  03-07-18  5:25a
AUTOEXEC BAT           638  03-07-18  5:16a
FILE2000        2,097,152,000  03-07-18  5:22a
FILE2045        2,144,337,920  03-07-18  5:19a
FILE4095        4,293,918,720  03-07-18  5:35a
COMMAND  COM        66,945  08-28-06 10:38p
FILE2049        2,148,532,224  03-07-18  5:26a
        11 file(s)   2,094,119,446 bytes
         1 dir(s)     15,996 Mega bytes free
C:\>lredir2 Z: C:
Z: = \\LINUX\FS\HOME\CHRIS\.DOSEMU\DRIVES\C\ attrib = READ/WRITE               ````
````

I'd like this to stop appearing in xterm. It only shows up when the big files are present.

````
ERROR: fatfs: file system full, /home/chris/.dosemu/drives/c
````

**Comment by stsp** [comment] 2018-03-07 10:56
You can stop this from appearing by not
exceeding the FAT capacity in the drives
that are in `$_hdimage`. You can use lredir2
to any large dirs, but `$_hdimage` is creating
FAT drives. I am planning to add a new option
to create redirected drives. But it would still be
a very bad idea to overflow your boot drive.
You should put your large files to non-boot drive.

**Comment by stsp** [comment] 2018-03-09 23:04
> Furthermore, the blocking files must start with [a-eA-E]. Files starting with [f-zF-Z] are not a problem.

I guess your files are blocking `emufs.sys` from
loading, as when they are [f-z], they are below
`emufs.sys` and do not harm.
I guess it was quite bad on you side to not mention
the
```
ERROR: fatfs: file system full, /home/chris/.dosemu/drives/c
```
from the very beginning.
Plus I suppose when the problem happens, there
are some errors from `config.sys` saying `emufs.sys`
not found or something like that. And you haven't
mentioned that either.
So essentially I think your problem is that you overflow
the boot drive. But it would still be good to know if
`emufs.sys` has something to do with this, as w/o
`emufs.sys` it should still work.

**Comment by severach** [comment] 2018-03-09 23:41
> errors from config.sys saying emufs.sys not found

Looking for this revealed the problem. I added `pause` to `autoexec.bat` so I could see `config.sys` errors and I damaged the `emufs.sys` line so it would produce an error. With the large files in `C:\` there is no `emufs.sys` error so the system does not run anything in `config.sys`. Once I move the large file away I can see the error and `lredir2` doesn't work.

````
Unsupported DOS version or EMUFS.SYS not loaded
````

Now the question is, why did this stop working with commit 14ac7ab ?

```
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
```

Is it enough to keep the large files out of the root dir so that emufs.sys can be loaded?

**Comment by stsp** [comment] 2018-03-09 23:53
> Now the question is, why did this stop working with commit 14ac7ab ?

I don't know yet.
See how it works w/o any large files and
w/o `emufs.sys` at the same time.

> Is it enough to keep the large files out of the root dir so that emufs.sys can be loaded?

But emufs.sys itself is not in a root dir normally.
So my guess would be no.

**Comment by severach** [comment] 2018-03-10 00:56
I think I've entered the [Scary Door](http://futurama.wikia.com/wiki/The_Scary_Door). Here's a brand new `.dosemu` and I've damaged the emufs.sys line.

````
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.8 installed.
CONFIG.SYS error in line 10
>>>devicehigh=e:\dosemu\emufsx.sys
             ^
Kernel: allocated 46 Diskbuffers = 24472 Bytes in HMA
 
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre8-20180308-144-gc1b7ae605
C:\>lredir2 Z: C:
Z: = \\LINUX\FS\HOME\CHRIS\.DOSEMU\DRIVES\C\ attrib = READ/WRITE
````

Now I add `aile{1024,1536}` for 2.5GB and this.
````
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
 
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre8-20180308-144-gc1b7ae605
C:\>   
````

No error because `config.sys` does not run.

Ok, new trick

````
install=d:\dosemu\lredir2.com -R z: d:
shellhigh=z:\command.com /e:1024 /p
install=z:\dosemu\lredir.com -f d: linux\fs\home\chris\d
install=z:\dosemu\lredir.com -f c: linux\fs\home\chris\c
````

Boot to empty `C:` drive and switch to my `C:` drive with `lredir`. Softlink `config.sys` and `autoexec.bat` so they are the same when the `C:` drive switches.

No more `file system full` errors and I can keep large files on what I see as `C:`.

**Comment by stsp** [comment] 2018-03-10 01:36
> No error because config.sys does not run.

That explains the LASTDRIVE problem.
Still unsure why did you got that for [a-e]
and not [a-c] large files. [d-e] should not
disable `config.sys` and only `emufs.sys`,
which should still work.

You don't need to softlink config.sys as I
suppose it will keep working from the original
drive anyway. You don't need to softlink
autoexec as instead you can change your
`shellhigh` a bit: remove `/p` from it and use
`/k y:\autoexec.bat` to run autoexec.bat from
any drive you want.

I think this can be closed.

**Comment by stsp** [comment] 2018-03-10 02:06
> and not [a-c] large files. [d-e] should not
> disable config.sys

But should disable `fdconfig.sys`.
Puzzle solved.

> Now the question is, why did this stop working with commit 14ac7ab ?

Because the redirection now happens
after `fdconfig.sys` is processed, and before
that change the redirection happened
before `fdconfig.sys`.
Now this is a clearly unwanted side-effect
that may break some existing setups. It
may be fixed by implementing the boot-D
proposal (boot from R/O drive D), but still
only for the new setups - old setups may
still suffer.
So right now I don't know what to do about
this. Either revert or people will hate the next
-pre for too many incompatible changes.

**Comment by stsp** [comment] 2018-03-10 02:10
The unwanted side-effect is that the
drive overflow was previously forgivable.
In fact it was probably never even encountered,
as these days we do not scan drive unless
DOS reads files from FAT.
So I guess the error message:
```
ERROR: fatfs: file system full, /home/chris/.dosemu/drives/c
```
was not there before the change in
question, which means this is a clear
regression. :( Basically there was no
FAT size limit, and now it is.

Ideas?

**Comment by severach** [comment] 2018-03-10 02:17
Live replacing the C: drive is confusing enough. `autoexec` on other drives or not linking would lead to confusion. People would edit `c:\fdconfig.sys` and `C:\autoexec.bat` and wonder why the edits have no effect. Besides, someday you're going to trample those files and I need my amended files to merge from.

**Comment by stsp** [comment] 2018-03-10 02:29
No, I was just suggesting you how to
avoid the linking of autoexec.bat. Its
not a general suggestion to others.

**Closed** 2018-03-10 02:32 UTC

**Comment by stsp** [comment] 2018-03-10 02:33
Should now be fixed.
Some artefacts like
```
ERROR: fatfs: file system full, /home/chris/.dosemu/drives/c
```
will remain for now, but it should work fine most of the time.

**Comment by stsp** [comment] 2018-03-10 11:11
> Is it enough to keep the large files out of the root dir so that emufs.sys can be loaded?

So as you correctly edited your comments to
mention `fdconfig.sys` instead of `config.sys`
and `emufs.sys` appears irrelevant, I can
provide a more meaningful answer, which is
"yes". :) As we do delayed cluster assignment,
the overflow only happens when DOS scans
root dir for `fdconfig.sys`. It won't scan in the
subdirs, so the problem will be avoided.
But for the same reason (delayed assignment)
I suspect the overflow error will go away now
too, so the problem should be (almost) fully fixed.
